### ISSUE TITLE
[Bug]: Reactivity issue when using vue-chartjs v4 with `chartjs-plugin-trendline`

### ISSUE THREAD

**Issue by mariadb-ThienLy** [apertureless/vue-chartjs#1006]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

I have a linear line chart and a button to toggle the visibility of the trendline. Showing the trendline works fine, but when I click the button again to hide the trendline, nothing happens. 
Perhaps the changes in the dataset property don't trigger chart updates.
I even try to update the chart via ref manually, but no luck.

It works fine without using vue-chartjs so I believe either my vue code is wrong or vue-chartjs has a bug in the reactivity system.

Here is the version with vanilla js https://codesandbox.io/s/working-trendline-q31h0o?file=/src/index.js

### Reproduction

https://codesandbox.io/s/vue-chartjs-demo-forked-kujr7m?file=/src/components/LineChart.vue:0-1463

### chart.js version

v3.9.1

### vue-chartjs version

v4.1.2

### Possible solution

As I mentioned, vanilla js works, so updating the dataset via ref works.

**Comment by AusHick** [comment]
A late bump to the issue, but I ran into something I believe is related to this on my own as well.

It seems that whatever is going on in the reactivity system, it only triggers a redraw of the chart on a shallow change.  Making a deep change like you did with `data.datasets[0].trendlineLinear` does not cause a redraw. In my case, I was trying to update values in `data.datasets[0].data` directly, to the same effect.

A sloppy PoC for this is to basically make your deep changes, followed by `data = JSON.parse(JSON.stringify(data))`, since this will create a deep copy of the ChartData, forcing redraw.

**Comment by apertureless** [comment]
Well chart.js per default is not reactive. `vue-chartjs` has some checks in place to update the chart on data changes. But there are many edge cases and limitations of watchers. 

The best way would be if you manually check for changes and then call `.update()` to update the chart.
