### ISSUE TITLE
[Bug]: Dynamically updating a chart

### ISSUE THREAD

**Issue by EFeru** [apertureless/vue-chartjs#1079]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Hi,

I would like to update dynamically my chart,  however the chart is not rendering as expected.

Expected behavior:
Every time "Change data" is clicked, a new data point is added to the chart and the chart is properly rendered. However, only on the first click it works. Only hiding and showing the data, triggers a chart refresh and correcly showing the data.

Can you please tell me what am I doing wrong? (see the attached sandbox link). Would be very much appreciated, thank you.
Related issue #846 

### Reproduction

https://codesandbox.io/p/sandbox/confident-morning-qq9x8c

### chart.js version

v4.4.1

### vue-chartjs version

v5.3.0

**Comment by apertureless** [comment]
Because your "random" data is not random.
If I click on "change data" and take a look at your console logs, its always the same data .

![image](https://github.com/apertureless/vue-chartjs/assets/4975917/30e5ea23-9939-41c0-87ea-6780cb722c70)

**Comment by EFeru** [comment]
Thanks for your answer @apertureless . I want to say that the data is changing by adding 1 extra data point for every click on "Change data" (you can see in the console).
If you click twice on the "My second Dataset" you will see the new points being displayed.
![image](https://github.com/apertureless/vue-chartjs/assets/24780745/ae33d008-4cc1-42bc-a902-7bd00cdb4c8c)

I also tryied the example you suggested and with at periodic function inside my child component the data is changing. So, I am not sure in seems like vue is not able to detect the change in the props that I am sending `props.data` for some reason.

**Comment by EFeru** [comment]
I cannot understand why changing the actual `data` like this
```js
function changeData() {
  count++
  var valueX = 'new' + count
  var valueY = 50 + count

  data.value.labels.push(valueX)
  data.value.datasets[0].data.push(valueY)
  console.log(data.value.labels)
  console.log(data.value.datasets[0].data)
  ```
  gives `Uncaught RangeError: Maximum call stack size exceeded`
  
![image](https://github.com/apertureless/vue-chartjs/assets/24780745/f9ad1049-f864-401b-990e-388eba665683)

**Comment by apertureless** [comment]
Because Chart.js itself is not reactive and you have to manually call the `.update()` function.
So we have a deep watcher in place to detect changes.  https://github.com/apertureless/vue-chartjs/blob/main/src/chart.ts#L65-L113

However the data property is a complex type with nested arrays. If you log out the whole data object you see that it is quite huge. So deep comparing in the watcher is expensive, but we need to do it. And we have to do some manual comparing if data really changed. 

I guess changing first the labels and then the data directly on the reactive prop will trigger too many updates.

In the first example you can also add a watcher to your prop in the chart component and then manually updating the chart with calling the `.update()` function on chart instance.

**Comment by EFeru** [comment]
I fixed it with plain `chartjs` and implementing a watcher. I didn't use `vue-chartjs`. I didn't investigare on how to approach it with `vue-chartjs`

Thanks for your help.

You can see the result here:
https://codesandbox.io/p/sandbox/confident-morning-qq9x8c

Uploading 2024-01-10 12-11.mp4…
