### ISSUE TITLE
run error on my mac pro

### ISSUE THREAD

**Issue by JasenWu** [apertureless/vue-chartjs#113]
![image](https://cloud.githubusercontent.com/assets/8563465/26346711/ac9c285a-3fd9-11e7-8c5e-482c3905397d.png)

**Comment by apertureless** [comment]
Have you accidently updated the dev dependencies? 

You could try to rename it to `OccurrenceOrderPlugin` because it got renamed. However with the current versions which are locked in the yarn.lock file, this should not happen. I also can't reproduce this. A clean git clone && yarn install && yarn run dev works fine for me.

**Comment by JasenWu** [comment]
now ,it is work well now ,thanks !
