### ISSUE TITLE
question:syntax with vue-loader

### ISSUE THREAD

**Issue by beebase** [apertureless/vue-chartjs#12]
Does anyone know some example syntax using vue-chartjs with vue-loader?
```
<template>..</template>
<script>..</script>
```

**Comment by apertureless** [comment]
Don't really get your question. The syntax should stay the same. Or are you running into problems?

**Comment by beebase** [comment]
I'm trying to make vue-chartjs work with quasar-framework, so might also be related to the customized webpack config.
Will first try with a vanilla vue-loader project.
Thanks

**Comment by apertureless** [comment]
Not sure right now if you can use the component.extend({}) syntax inside vue single file components. 
`export default Bar.extends({})`


However if I recall right, there is an [extends](https://vuejs.org/api/#extends) property.

```javascript
// MyChart.vue
<script>
import {Bar} from 'vue-chartjs'

export default {
  extends: Bar
  data () { ... }
}

</script>
```

This could work.

But I don't see a problem mixing vue and js compoentns. You don't really need the benefits of vue single file components, because you normally don't have much styling or templates going on there.

Because the BaseChart classes got the template tag with a canvas and styling of the charts are over the options object.

So it should not be a problem using js files instead. And create the chart components with normal js files. You can then normally import them as components into your single-vue-file.vue compoentns.

However I guess this is a more vue-loader related question.

**Comment by beebase** [comment]
Thanks!
.extends was in fact the thing I was running into but with your info I might be able to solve this. Will post here when I find the right syntax.

**Comment by beebase** [comment]
(vuejs 1.x)

1. CommitChart.js
![img2357](https://cloud.githubusercontent.com/assets/446089/19468256/a569719c-9515-11e6-94dc-29d85442d4aa.jpg)

2. parent component
![img2358](https://cloud.githubusercontent.com/assets/446089/19468270/bef6590e-9515-11e6-840c-c0aa4bac4e59.jpg)

3. thanks!
![img2355](https://cloud.githubusercontent.com/assets/446089/19468289/d1860768-9515-11e6-9bf7-c1a782faf672.jpg)
