### ISSUE TITLE
Standalone chartjs build (don't include moment.js)

### ISSUE THREAD

**Issue by CalebKester** [apertureless/vue-chartjs#124]
### Expected Behavior
Moment.js shouldn't be included

### Actual Behavior
Moment.js appears on my package.lock file and gets bundled in my build

### Environment
- vue.js version: 2.3.3
- vue-chart.js version: 2.6.0
- npm version: 5.0.3
- webpack: 2.5.1

Can you help me figure out how I configure this correctly so that I only get the standalone chart.js build: https://github.com/chartjs/Chart.js/blob/3e94b9431a5b3d6e4bfbfd6a2339a350999b3292/docs/getting-started/installation.md . Moment.js is a very heavy package and if I can avoid including it in my site I'll gladly do that. The documentation makes it sound like treeshaking can do this but I'm just using the vue webpack cli and it's still coming through.

Thanks

**Comment by apertureless** [comment]
Hey @CalebKester 

to be honest, I am not completely sure 🤔  if this is possible.

I don't think that treeshaking will work. Because it only works on es modules.  And neither Chart.js nor moment.js are available as es modules. AFAIK.

Thats a reason, why I have extra es modules output in `vue-chartjs` . https://github.com/apertureless/vue-chartjs/blob/develop/package.json#L39-L42

The problem is, that I am simply importing chart.js over `import Chart from 'chart.js'` and I guess it will grab the version with moment.js included. However I am not completely sure, because the [pasckage.json](https://github.com/chartjs/Chart.js/blob/master/package.json#L7) of Chart.js seems weird, as the index is set to the `src/Chart.js` and not to the bundled dist files.

So I guess, if you're using `import` you can't grab the standalone one. However I will check the docs of Chart.js

**Comment by throrin19** [comment]
I Have the same problem Here.

I load chartJs like that :

```
import { Bar } from 'vue-chartjs';
```

But, in compilation, I have momentJS in the bundle :/

**Comment by apertureless** [comment]
That is because if you import `Chart from 'chart.js'` you will get the bundled one (with moment.js).
There are some issues at chart.js to kill moment.js and replace it with date-fns.  However I don't know if it will happend.

I would love to change that, however it would be confusing to break with the standard behaviour of the chart.js npm package. So the solution needs to be on user side right now.

## 💍  Solution

You need to add an alias to your webpack config, so it will grab the standalone version

**webpack.config.js**
```js
resolve: {
    alias: {
      'chart.js': 'chart.js/dist/Chart.js'
    }
```

This way it will grab the standalone version.

![xj3Ie4rLNuLSM](https://media3.giphy.com/media/xj3Ie4rLNuLSM/giphy.gif?cid=e1bb72ff5a788a53626c387351d64820)

**Comment by throrin19** [comment]
Thanks. It works

**Comment by himynameisubik** [comment]
Sorry, I might be doing something wrong but I can't get this to work:
**vue.config.js**
`    configureWebpack: {
      resolve: {
          alias: {
              'chart.js': 'chart.js/dist/Chart.js'
          }
      }`

With that moment.js still ends up in my chunk-files. Any idea?

**Comment by apertureless** [comment]
I think this is not possible anymore. 
Because it was kind of a bug of chart.js that they did not include momentjs in the `chart.js/dist/Chart.js` build.

Not as far as I understand it is bundled in both version.

**Comment by himynameisubik** [comment]
Oh damn, really? So I'm stuck with having moment.js in my project even though I never use it. It's literally the largest chunk in my whole project. Thanks for your answer though!

**Comment by himynameisubik** [comment]
Seems it works fine. No issues for now.

**Comment by apertureless** [comment]
I think it will work as long as you do not use any chart.js features that rely on momentjs.

**Comment by himynameisubik** [comment]
Yes of course. But that would‘ve been the same with only using the standalone in earlier version, no?

**Comment by J3m5** [comment]
Hi! 

First of all, I would like to thank you for vue-charts, it's really great!

The standalone build does not include moment as mentioned [here](https://www.chartjs.org/docs/latest/getting-started/installation.html#stand-alone-build) since [2.8.0](https://github.com/chartjs/Chart.js/releases/tag/v2.8.0), it was implemented in the PR https://github.com/chartjs/Chart.js/pull/5978 .

This is also to allow us to choose an other date library, now there is adapters, as implemented in https://github.com/chartjs/Chart.js/pull/5960 . There are two adapters at this time, one for [luxon](https://github.com/chartjs/chartjs-adapter-luxon) and another for [date-nfs](https://github.com/chartjs/chartjs-adapter-date-fns).

It would be really nice to add a way to select the build we want and use the adapters we'd like.

I'm planning to switch to date-fns as soon as I can to reduce the size of my builds by using Date-nfs because it can benefits from treeshaking and is lighter than moment.

**Comment by himynameisubik** [comment]
Strange, building my project with the standalone (general npm package) adds moment to it. Maybe I need to change my chartjs npm installation.

**Comment by J3m5** [comment]
In fact, it is included by default if you use webpack so you are right, you need to manually remove it as stated [here](https://www.chartjs.org/docs/latest/getting-started/integration.html#bundlers-webpack-rollup-etc).

**Comment by himynameisubik** [comment]
Yes exactly, that‘s what I did and commented here: https://github.com/apertureless/vue-chartjs/issues/124#issuecomment-480539362

**Comment by SergeiMinaev** [comment]
I use rollup. After excluding moment.js with `external: ['moment']` I got this error:

`SyntaxError: import declarations may only appear at top level of a module`

because there was  `import { moment } from 'moment'; ` at top of my bundle.js:

This plugin helped me: https://github.com/proteriax/rollup-plugin-ignore
Notice: 'ignore' plugin should be placed before others. Also, there is no need to use `external: ['moment']` if you use rollup-plugin-ignore.

My rollup.config.js:
```
...
import ignore from "rollup-plugin-ignore";
...
plugins: [
  ignore(['moment']),
  ...
]
```
