### ISSUE TITLE
Chart doesn't load in bootstrap tab

### ISSUE THREAD

**Issue by mwei0210** [apertureless/vue-chartjs#157]
## Expected Behavior
Charts in both active and inactive tab to load

### Actual Behavior
Only chart in active tab load but not the inactive tab

**Comment by apertureless** [comment]
Please provide a codepen or jsfiddle for reproduction.

**Comment by mwei0210** [comment]
See if this is sufficed, 

> <div class="tab-content">
    <div class="tab-pane active" id="tab-1">
        <chart></chart>
    </div>
    <div class="tab-pane" id="tab-2">
        <chart></chart>
    </div>
</div>

Chart in the first tab-1 works but when i switch to tab-2, the chart doesn't show at all. Thanks

**Comment by apertureless** [comment]
Hey, I need a working example to debug it. 

Are you using a vue-bootstrap lib? Or pure bootstrap?

**Comment by mwei0210** [comment]
Its on pure bootstrap. May need sometime setting the reproduction up..

**Comment by apertureless** [comment]
You can easy load it in codepen just add the bootstrap files the vue-chartjs cdn and you can start.
Check out the https://codepen.io/apertureless/pen/vxWbqB?editors=1010

**Comment by mwei0210** [comment]
Try navigating between tabs, only tab 1 is loaded whereas other tabs don't. 
[https://codepen.io/mwei0210/pen/ayvoyO](url)
Thanks

**Comment by apertureless** [comment]
Thanks for this!

Well, the problem is, how chartjs works if you pass `responsive: true`. 
What `responsive: true` does, it so set the width and height of the chart, based on the outer div.

In your example it's the `tab-pane` . However, because of the tabs, only the active tab has a height and width, as the other hidden tabs are set to `display: none` so their height and width is 0.

But the vue chart component gets loaded and chartjs sets the chart height and width to 0.
If you now click on the second tab, the class sets it to `display: block` However the chart can't detect that change.

There are **two**  possible solutions for you.

1. You set `responsive: false` and may set an fix width and height. This way you will see the charts if you change the tabs.

2. You use a vue based tabbar. This whay you could add a `v-if` to the chart and only mount it if the tab is open, so chart.js can detect the width and height of the outer div.

**Comment by mwei0210** [comment]
Got it! Thanks!

**Comment by fmmattioni** [comment]
For anyone that is looking for a solution now, you can simply add `lazy` to `<b-tab>` and it works.
