### ISSUE TITLE
Options being ignored

### ISSUE THREAD

**Issue by peteringram0** [apertureless/vue-chartjs#160]
There seems to be an issue with disabling the legend with the latest version. This was working before for me.

Chart rendered:
![screen shot 2017-07-31 at 16 22 46](https://user-images.githubusercontent.com/6588942/28784879-9b09e5a0-760c-11e7-8d79-941c44c79d86.png)

Constants.js file
````javascript
export default {
    chartOptions: {
        legend: {
            display: false
        }
    }
}
````

.vue file
````javascript
import {
    Bar,
    mixins
} from 'vue-chartjs'

import Constants from '../../Constants';

const { reactiveData } = mixins;

export default Bar.extend({
    mixins: [reactiveData],
    data() { 
        return {
            chartData: null
        }
    },
    watch: {
        // watching my external data-set and updates this.chartData
    },
    mounted() {
        this.renderChart(this.chartData, Constants.chartOptions);
    }
});

````

**Comment by apertureless** [comment]
What was the previous version you were using? 
Are you **now** using the latest?

**Comment by peteringram0** [comment]
I am using the latest version now yes. Sorry what i about the previous version is in-accurate.

This is happening when using the reactiveData mixins. If i remove it the legend is hidden.

**Comment by apertureless** [comment]
Oh okay. 
Yeah the chart options and the reactive mixins are a bit weird. Because in some cases, if you add new data and the chart can't update and has to re-render and it calls `renderChart(this.chartData, this.options)`

Right now I don't really know how to "clean" this up, because I don't know which arguments get passed from the user. So if you don't set your chart options in a local data attribute called `options` it will re-render the chart without options.

So a workaround for you would be to declare options in your data model.

```js
import {
    Bar,
    mixins
} from 'vue-chartjs'

import Constants from '../../Constants';

const { reactiveData } = mixins;

export default Bar.extend({
    mixins: [reactiveData],
    data() { 
        return {
            chartData: null,
            options: Constants.chartOptions
        }
    },
    watch: {
        // watching my external data-set and updates this.chartData
    },
    mounted() {
        this.renderChart(this.chartData, this.options);
    }
});
```

This should fix it.

**Comment by peteringram0** [comment]
Ah yer got it, thats working, thanks.
