### ISSUE TITLE
Chart height definition inside the component

### ISSUE THREAD

**Issue by strebl** [apertureless/vue-chartjs#18]
Hi @apertureless 

Thanks for your great work!

I have a question. Can I set the height within the component itself?
I can't set `this.height = 200` because you can't modify a prop inside a component.
I know about the container option and the prop. But I'd like to set the height of the chart depending of the data it has.
Sure I can calculate that in the prop, but I think the logic should be in my component.

**Comment by apertureless** [comment]
Hi @strebl ,

mh I guess it is not really possible. You could try to overwrite the props default value. Because you're extending the component, you have actually access to the props and data. So it could be possible to overwrite the default value of the height. 

However this would be only a static change. For one of your components. You could not change it dynamically, based on the data you feed it.
