### ISSUE TITLE
Why default Chart.js styles are overridden?

### ISSUE THREAD

**Issue by ihrankouski** [apertureless/vue-chartjs#189]
Why default Chart.js styles are overridden?
- like here in [Bar](https://github.com/apertureless/vue-chartjs/blob/46569a89cbd1e4895add26509121cc727e047e50/src/BaseCharts/Bar.js#L63)
- or here in [Line](https://github.com/apertureless/vue-chartjs/blob/46569a89cbd1e4895add26509121cc727e047e50/src/BaseCharts/Line.js#L58)

I think it's not cool when you run your code and see that your chart looks different compared to the same one in Chart.js docs - then it takes time to find out how to reset the styling to customize the way you want...

**Comment by apertureless** [comment]
Well its more a legacy thing. I created this actually for personal use and set some default styles to save time.

However I don't see a problem overwriting them. Most people will not use the default styles of chart.js 

And you see in the repo screenshots how they will look.

**Comment by ihrankouski** [comment]
It's not a problem, that's rather a matter of taste and to me, it seems to be an unexpected behavior for a wrapper. Basically I'm ok with default styling and in particular it took some time to find out why grid lines are not getting displayed.

**Comment by eddiemf** [comment]
I see this as a problem, it took me a good time to figure out what I was doing wrong because the gridLines were not showing, and everywhere in the official docs the gridLines are showing without any configuration. So I searched this and found that it gets overwritten and it's not exposed in the docs or anywhere else.

It's really not a good idea to override default configuration in a wrapper when you depend on the official docs that explicitly says that the display property of the gridLines are `true` by default (and any other prop that might be overwritten as well).

Or at least make it clear in the docs that you are overriding it (I had to search in source code), so when people see things are not working the way they expect they will quickly figure out that some styles are being overwritten.

Anyways, that's just my opinion :)
