### ISSUE TITLE
Updating the height using reactive properties

### ISSUE THREAD

**Issue by anneliujohnston** [apertureless/vue-chartjs#252]
My code allows the user to build graphs on the fly using search criteria.  If they adjust the search criteria, the graph will change according to the new data returned.  I also determine the `maintainAspectRatio` and the `height` depending on the number of rows in my HorizontalBar chart.

```javascript
   <impact-report-graph ref="impactReportGraph"
     :chart-data="impactReportGraphData" :options="impactReportGraphOptions"
     :height="graphHeight">
   </impact-report-graph>
    ...
    graphHeight: function () {
      if (this.groups !== undefined) {
        if (this.groups.length > 0 && this.groups.length <= 10) {
          return 520
        } else if (this.groups.length <= 20) {
          return 720
        } else if (this.groups.length <= 30) {
          return 920
        } ...
    },
    impactReportGraphOptions: function () {
      return {
        ....
        maintainAspectRatio: (this.groups.length > 60),
        ....
      }
   }
```
The first graph always displays correctly; however when the query is rerun and the data set returned changes sizes, the graph size is incorrect.   The height of the canvas is correctly updated, but the style is not.  Is this a bug or is there something I am missing.  Alternatively, is there a workaround I can use in the meantime.  I've tried to destroy and re-render the graph, but I can never reset the height.

### Expected Behavior
```html
<canvas id="horizontalbar-chart" width="910" height="3617" class="chartjs-render-monitor" style="display: block; width: 910px; height: 3617px;"></canvas>
```
### Actual Behavior
```html
<canvas id="horizontalbar-chart" width="910" height="1590" class="chartjs-render-monitor" style="display: block; width: 910px; height: 520px;"></canvas>
```

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

TIA!

**Comment by apertureless** [comment]
Do you have the `responsive: true` option set?
If so, you can't change the height or width of the canvas element. Because it will grow to the size of the containing container.

http://www.chartjs.org/docs/latest/general/responsive.html

Furthermore, I don't think it will work to change the options because as far as I know chart.js does not detect changes in the options.

So if you change the options like the `maintainAspectRatio` you will need to rerender it.
If you just want to change the height, you can do it with the dynamic styles. Which are introduced in v2.8 https://github.com/apertureless/vue-chartjs/releases/tag/v2.8.0

It will pass an styles object to the chart and change the height of the div.

```js

<template>
     <div>
       <line-chart :styles="myStyles"/>
       <button @click="increase()">Increase height</button>
     </div>
</template>

<script>
export default {
  data () {
    return {
      height: 300
    }
  },
  methods: {
    increase () {
     this.height += 10
    }
  },
  computed: {
    myStyles () {
      return {
        height: `${this.height}px`,
        position: 'relative' // ☝ Important!
      }
    }
  }
}
</script>
```

**Comment by anneliujohnston** [comment]
Thanks for your quick reply!  I will try adding the style.  

Another option, I was trying was to call `this._chart.destroy()` and then `this.renderChart`; however, I could not figure out a way to update the `height` option again on the render.  Is there a way to pass in a new `prop` into the chart on render?

**Comment by apertureless** [comment]
Well if you pass the `:height` attribute it will be set on the canvas directly. And is only working if you have `responsive: false` set.

If you destroy the chart.js instance over `this.$data.chart.destroy()` and then call `this.renderChart()` the new height should be set as it's set as the component prop.

The problem is, that the `width` and `height` attributes are set directly on the canvas element. Chart.js grabs these and then sets its own styles. Thats why you can't change them on the fly. And need to destroy the old instance and set the new one.

With `responsive:true` chart.js automatically set's the size of the canvas. However I guess the computed styles object should work.

You could make something like this:


```js
 <impact-report-graph ref="impactReportGraph"
     :chart-data="impactReportGraphData" :options="impactReportGraphOptions"
     :styles="graphStyles">
   </impact-report-graph>
    ...
   computed: {
     graphHeight () {
        if (this.groups !== undefined) {
            if (this.groups.length > 0 && this.groups.length <= 10) {
              return 520
            } else if (this.groups.length <= 20) {
              return 720
            } else if (this.groups.length <= 30) {
              return 920
            } ...
         },
        graphStyles () {
         return {
           height: `${this.graphHeight}px`, // px, rem, em
           position: 'relative' // ☝ Important!
         }
       }
   }
    
....
    impactReportGraphOptions: function () {
      return {
        ....
        maintainAspectRatio: (this.groups.length > 60),
        ....
      }
   }

...

watch: {
    'impactReportGraphOptions': function () {
       this.$data.chart.destroy()
       this.renderChart(impactReportGraphData , impactReportGraphOptions)
     }
}

```

**Comment by anneliujohnston** [comment]
Thank you so much for the help!  I got it the dynamic sizing working!
