### ISSUE TITLE
Fresh install error

### ISSUE THREAD

**Issue by kidii** [apertureless/vue-chartjs#254]
Hi!

I did a fresh install, but I got an error. I deleted the node_modules folder, and run npm install, but nothing.

### Actual Behavior

ERROR in ./~/vue-chartjs/package.json
Module parse failed: /Applications/MAMP/htdocs/test/node_modules/vue-chartjs/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
| {
|   "_from": "vue-chartjs",
|   "_id": "vue-chartjs@3.0.2",
|   "_inBundle": false,
 @ ./~/vue-chartjs/es/index.js 11:0-37
 @ ./~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/Home.vue

### Environment
- vue.js version: 2.0.1
- vue-chart.js version: 3.0.2
- npm version: 5.5.1

**Comment by apertureless** [comment]
Whats your environment? Webpack ?

**Comment by kidii** [comment]
Laravel 5.3 with these:
    "laravel-elixir": "^6.0.0-15",
    "laravel-elixir-browserify-official": "^0.1.3",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-webpack-official": "^1.0.10",

**Comment by apertureless** [comment]
Oh laravel-elixir is the old one right? 
I am a bit confused, are you using webpack or browserify to bundle your javascript?

Can you provide a minimal repo for reproduction? As the new laravel stuff is always with Laravel Mix. Which works fine as far as I remember.

**Comment by kidii** [comment]
I'm using webpack.
I can't provide any repo :/ If I add this line:
import { Bar } from 'vue-chartjs'
I got the following error, what I wrote above.

**Comment by apertureless** [comment]
Hm, without a reproduction of your build environment it's hard to say where the error lies.

1. Do this happen to other vue packages, too?
2. Are you using the babel presets?
3. Have you added the vue-loader / plugin ?

```js
Elixir.webpack.mergeConfig({
    babel: {
        presets: ['es2015'],
        plugins: ['transform-runtime'],
    },
    module: {
        loaders: [{
            test: /\.vue$/,
            loader: 'vue'
        }]
    }
});
```

You could also try to set babel als the for the vue files instead of buble which is the default? I think...

I generally would recommend to upgrade / replace Elixir with Laravel Mix which is the new one.
As Elixir is not maintained anymore and running on the webpack beta `2.1.0-beta.15 - 2.1.0-beta.22` Which could cause problems.

And the `laravel-elixir-vue-2` package is also outdated and not maintained anymore.

You will btw. also get a warning of an unmet peerDependency / version mismatch, as you're running an older version of vue.

**Comment by kidii** [comment]
Thank you for everything but rather installed Laravel 5.4 and now it's working!
