### ISSUE TITLE
hello a q about reactivity

### ISSUE THREAD

**Issue by SerjoA** [apertureless/vue-chartjs#28]
cant get to make the reactive prop to update the chart although it shows that the data has been changed the chart wont update or redraw
can anyone please post example , btw iam on vue 2.1

**Comment by apertureless** [comment]
Hey,

here is an example: https://github.com/apertureless/vue-chartjs/blob/master/src/examples/ReactiveExample.js

which is also used on the demo page.

If you have issues, please provide a jsfiddle or a minimal repo for reproduction.

However the mixins are very generic. It may be better if you implement an update cyrcle yourself.

Heres the source of the mixin: https://github.com/apertureless/vue-chartjs/blob/master/src/mixins/reactiveProp.js

You can copy paste it as a local mixin and try to add debug output. See if the watcher triggers and if 

if (JSON.stringify(newDataLabels) === JSON.stringify(oldDataLabels)) works.

**Comment by SerjoA** [comment]
checked examples but still wont work, heres a jsfiddle
https://jsfiddle.net/Solutionseje/7bgqzw4s/

**Comment by SerjoA** [comment]
i solved it with emitting events and updating chart manually
but is there another way?

**Comment by SerjoA** [comment]
now i have another problem when moving through routes, without keep-alive

Uncaught (in promise) TypeError: Cannot read property 'getContext' of undefined
    at VueComponent.renderChart (eval at <anonymous> (app.js:1128), <anonymous>:41642:59)
    at VueComponent.boundFn [as renderChart] (eval at <anonymous> (app.js:1128), <anonymous>:338:15)
    at VueComponent.updtChrt (eval at <anonymous> (app.js:2274), <anonymous>:23:12)
    at Vue$3.boundFn (eval at <anonymous> (app.js:1128), <anonymous>:340:13)
    at Vue$3.Vue.$emit (eval at <anonymous> (app.js:604), <anonymous>:2393:16

**Comment by apertureless** [comment]
Hey @SerjoA 

## Reactivity 
well events are one way to go. Chartjs has no automatic detection if data changes. So you actually always have to manually update the chart / rerender. 

Generally there are two ways: one is over events, the other is over the watcher (the mixins are using it) However it can be, that you have to add deep: true to the watcher, because if the data is rather complex it would not see a change.

Thanks for the jsfiddle.

Eh, there are two mixins reactiveProp and reactiveData. 

You should use reactiveData only if you store your chartdata into a variable in the data function. Thats for, if you get your data over an api.

If you pass your chartdata as a prop like in your jsfiddle, you should use the reactiveProp mixin.

## vue-router

Never used it with vue-router. Do you have a minimal repo to reproduce the error? Hard to debug it without seeing the code.

**Comment by SerjoA** [comment]
Thnx alot for the info, I'll try to post my code with vue router, ATM I am sick but will do that when I've got a chance, solved all problems BTW with events, added update chart upon event because the mixins somehow didn't work, plus my update chart function basically does, context= chart-id, new chart (context, data) and it worked

**Comment by SerjoA** [comment]
Thnx for the repo, you are awesome

**Comment by apertureless** [comment]
Did you tried both mixins? Also the `reactiveProp` one?

What are you doing, is creating a new chart instance if new data arrives.
Which is not a good idea, because it may not destroy the old instances properly.

You actually need only to call `this._chart.update()`

**Comment by SerjoA** [comment]
thank you  for the info, will try it and update you, still sick :(

**Comment by SerjoA** [comment]
hi, i tried this._chart.update() works good

**Comment by SerjoA** [comment]
thank you

**Comment by apertureless** [comment]
Ok, cool.
So can this issue be closed?

**Comment by SerjoA** [comment]
Yes thank you
