### ISSUE TITLE
Vertical Bar Chart: Strange behavior wehn barchart when dataset has only one bar to display

### ISSUE THREAD

**Issue by AndreaMinato** [apertureless/vue-chartjs#285]
## Case

Bar Chart with weekdays from Monday to Sunday and only Monday has values on the dataset.

### Expected Behavior (2.8.6 -)
I want to see the bar over the monday label like this

![image](https://user-images.githubusercontent.com/15440218/34720020-817688f4-f53d-11e7-9d05-3e63edb7aedd.png)

### Actual Behavior (2.8.7 +)
I see the bar between Tuesday and Wednesday labels like this

![image](https://user-images.githubusercontent.com/15440218/34720001-59ded7b0-f53d-11e7-9563-0d91202148e8.png)

### Environment
- vue.js version: 2.5.13
- vue-chart.js version: 2.8.7 to 3.0.0 +

**Comment by apertureless** [comment]
Can you provide a link for reproduction? codepen / jsfiddle / webpackbin ?

However I think the is related to the updated chart.js lib which got updated to 2.7.0

https://github.com/chartjs/Chart.js/releases/tag/v2.7.0

Because from 2.8.6 up to 2.8.7 only the dependencies were updated.
I guess you have to pass some options which got removed as default options from chart.js

Have you checked the configuration of barcharts? http://www.chartjs.org/docs/latest/charts/bar.html#configuration-options

**Comment by AndreaMinato** [comment]
Here is the link to codepen
https://codepen.io/anon/pen/GyQrmr?editors=1010

**Comment by apertureless** [comment]
Hm, yeah this seems to be buggy. I guess its because you have more labels then datasets.
However, you should report this directly to chartjs. As this is imo a bug in chart.js directly, rather then vue-chartjs
