### ISSUE TITLE
Same "column" size for all charts

### ISSUE THREAD

**Issue by manelmendez** [apertureless/vue-chartjs#340]
I use an HoritzontalBar component for all my charts in a list of items. So when I render the charts every one have a different number of columns in one of the axis.

There's a way to set the same "column width" to all the charts? (I still don't find the solution)

![image](https://user-images.githubusercontent.com/10993997/38420887-98ab8a90-39a5-11e8-9f72-188f869e30cf.png)

![image](https://user-images.githubusercontent.com/10993997/38420904-a1195d42-39a5-11e8-8dd4-c83fe0613f4d.png)

I expect the same width in the red lines

Thanks for the help!

### Environment
- vue.js version: <2.4.4>
- vue-chart.js version: <3.2.1>
- npm version: <5.8.0>

**Comment by apertureless** [comment]
If you check the [Chart.js docs](http://www.chartjs.org/docs/latest/charts/bar.html#configuration-options) you can set the `barThickness`, `maxBarThickness`, `categoryPercentage`, `barPercentage ` and more stuff. I guess thats what you are looking for ✌️

**Comment by manelmendez** [comment]
Thanks for your help! I used those properties, but that only modifies the "bar", not the whole "column" that contains the bar. What I want is to have a column of the same size for all the tables and that the tables are more or less large depending on the number of columns that you have.

**Comment by apertureless** [comment]
So with `column` you actually mean the `row` right? Because your red line, is surrounding the individual row.

You can control the category with the settings: http://www.chartjs.org/docs/latest/charts/bar.html#barpercentage-vs-categorypercentage

If you want to remove the spacing between the bars, so they take up the full space, you have to set:

```
categoryPercentage: 1.0,
barPercentage: 1.0
```

For further questions please check out the official [Chart.js repo](https://github.com/chartjs/Chart.js) as this question is more related to core chart.js functions, rather then the vue implementation.

**Comment by manelmendez** [comment]
Actually, what I want is to make those rows of the size that I want (the same for all the graphics), not fill them with the bar, but surely you are right and it is more a question related to the official repository
