### ISSUE TITLE
Why not make BaseChart usable directly? I means , now I must firstly create a component that exents a Basechart...

### ISSUE THREAD

**Issue by jungor** [apertureless/vue-chartjs#342]
none

**Comment by apertureless** [comment]
Well because it gives you more control over your chart.
The Basechart is doing some boilerplate work for you. 

But because you are creating own chart components, you have full control over them and also over the underlying chart.js instance. You can extend the chart.js functions, add plugins, extend the base prototypes and many more things. 

If you just want one component for all, check out https://github.com/SeregPie/VueChart

**Comment by jungor** [comment]
Got it, 3Q~
