### ISSUE TITLE
Chart-canvas not updating after nextTick

### ISSUE THREAD

**Issue by huhabab** [apertureless/vue-chartjs#346]
Hello there,

I'm trying to export the canvas-imagedata of a chart separated by its dataSets, to do so I set the .hidden attribute to true and call the update() routine, call the nextTick of vm and then capture the canvas.

The Chart displays everything correctly after the code is executed and some time (couple of ms) has passed. But the canvas directly after nextTick looks like the old one.

Basically, what I'm trying to do (simplified):
`

        getChartImage(o){
          o.images.push(o.destinationCanvas.toDataURL("image/jpeg"));
          downloadResults(o.images);
        }

        o.ci.getDatasetMeta(0).hidden = true;
        o.ci.update();
        vm.$nextTick(getChartImage(o));
`
### Expected Behavior
I would have guessed that the next tick renders all changes and uses as much time as it needs to.

### Actual Behavior
After using a setTimeout calling the getChartImage-function everything works fine, so I assume the rendering process of the Chart takes longer than the nextTick needs, but that's just a shot in the dark.

### Environment
- vue.js version: 2.5.13
- vue-chart.js version: 3.1.0

**Comment by apertureless** [comment]
Hey @huhabab 

well, `nextTick()` will not work here. 
The reason is pretty simple, `nextTick()` works only if you modify the DOM.
Or Vue.js modifies the DOM. So like changing a variable that gets rendered, adding child nodes and so on.

However Chart.js is pure Canvas based. So you have only the `<canvas>` element and Vue.js does not see any changes inside the canvas element.

---

I guess the only way would be to set a small timeout before you render your image.
Thats the way I've done it in [npm-stats](https://github.com/apertureless/npm-stats/blob/develop/src/components/BarChart.vue#L112-L114)

You can also try the internal [tobase64image](http://www.chartjs.org/docs/latest/developers/api.html#tobase64image) function which comes with Chart.js
