### ISSUE TITLE
Using  chartjs-plugin-datalabels

### ISSUE THREAD

**Issue by HKskn** [apertureless/vue-chartjs#358]
Is it possible to use chartjs-plugin-datalabels plugin with vue-chartjs?

**Comment by apertureless** [comment]
Sure.
Just install it and imort it into your file. It should work out of the box. 
Otherwise you have the possibility to either add local plugins via `this.addPlugin()` or a prop.

http://vue-chartjs.org/#/home?id=inline-plugins

**Related issues:** https://github.com/apertureless/vue-chartjs/issues/94 , https://github.com/apertureless/vue-chartjs/issues/86
