### ISSUE TITLE
Min value not working in Line chart

### ISSUE THREAD

**Issue by oswaldofreitas** [apertureless/vue-chartjs#361]
### Expected Behavior
Show zero as minimum value in y-axis of Line chart.

### Actual Behavior
I can see zero for a moment, but after the date is rendered the minimum value gets an dynamic value from the data.

### Environment
- vue.js version: 2.5.2
- vue-chart.js version: 2.7.1
- npm version: 6.0.1

This is what I tried to do:
```
import { Line, mixins } from 'vue-chartjs'

const { reactiveProp } = mixins

export default {
  extends: Line,
  mixins: [reactiveProp],
  mounted () {
    this.renderChart(this.chartData,
      {
        responsive: true,
        maintainAspectRatio: true,
        scales: {
          yAxes: [{
            ticks: {
              suggestedMin: 0
            }
          }]
        }
      }
    )
  }
}
```

**Comment by apertureless** [comment]
If you are using the reactiveProp mixin you need to store your options in an `options` object.
The reason is quite simple: The reactive mixin will either call `update()` which would work fine. But it also could call `this.renderChart()` in this case it needs the parameters as local variables, because it would call `this.renderChart(this.chartData, this.options)` 

```js
import { Line, mixins } from 'vue-chartjs'

const { reactiveProp } = mixins

export default {
  extends: Line,
  mixins: [reactiveProp],
  data: () => ({
   options: {
        responsive: true,
        maintainAspectRatio: true,
        scales: {
          yAxes: [{
            ticks: {
              suggestedMin: 0
            }
          }]
        }
      }
  }),
  mounted () {
    this.renderChart(this.chartData, this.options)
  }
}

**Comment by oswaldofreitas** [comment]
Worked. Thanks man!

Very quick response :)
