### ISSUE TITLE
Vue-chartjs Instance

### ISSUE THREAD

**Issue by urvi2429** [apertureless/vue-chartjs#367]
So i am working on to add lable plugin in vue-chart js. In order to work it i want vue-chart.js instance.
How to get vue-chart js instance. I tried this.$chart._chart but it don't works. Here is my code.

const totalizer = {
        id: 'totalizer',
        beforeUpdate: chart => {
            let totals = {}
            let utmost = 0

            this._data._chart.myData.datasets.forEach((dataset, datasetIndex) => {
                if (this._chart.isDatasetVisible(datasetIndex)) {
                    utmost = datasetIndex
                    dataset.data.forEach((value, index) => {
                        totals[index] = (totals[index] || 0) + value
                    })
                }
                console.log("chart instance is ::" + dataset)
            })

            this._data._chart.$totalizer = {
                totals: totals,
                utmost: utmost
            }
        }
    }

**Comment by apertureless** [comment]
`this.$data._chart` is the current chartjs instance.
It is only available in your chart component where you extend the vue-chartjs chart and it is only available after you call `this.renderChart()` . 

Your code snippets does not help a lot, because its pretty much out of context. And you don't use `this.$data._chart` anywhere.

You also need to be sure that in your plugin `this` refers to the vue instance and not a own prototype.

**Comment by urvi2429** [comment]
This is the updated snippet. So totalizer is my plugins method.


const totalizer = {
        id: 'totalizer',
        beforeUpdate: chart => {
            let totals = {}
            let utmost = 0

            this.$data._chart.myData.datasets.forEach((dataset, datasetIndex) => {
                if (this._chart.isDatasetVisible(datasetIndex)) {
                    utmost = datasetIndex
                    dataset.data.forEach((value, index) => {
                        totals[index] = (totals[index] || 0) + value
                    })
                }
                console.log("chart instance is ::" + dataset)
            })

            this.$data._chart.$totalizer = {
                totals: totals,
                utmost: utmost
            }
        }
    }

**Comment by urvi2429** [comment]
And here is how my plugins look like.


plugins: {
                        datalabels: {
                            formatter: (value, ctx) => {
                                const total = ctx.this.$data._chart.$totalizer.totals[ctx.dataIndex]
                                console.log("total is "+total)
                                return total
                            },
                            align: 'end',
                            anchor: 'end',
                            display: function(ctx) {
                                return ctx.datasetIndex === ctx.this.$data._chart.$totalizer.utmost
                            }
                        }

                    }
                },
                plugins: [totalizer],

**Comment by apertureless** [comment]
Your code does not make sense.
You have your chart context with `ctx`. You can't `ctx.this.$data._chart`.

Again: `this.$data._chart` is the saved chart instance you created with `this.renderChart()` which is saved as a vue data prop. 
This is basically this: 

```js
export default {
	data: () => ({
      _chart: null
    }),
    mounted () {
      this.$data._chart = new Chart({})
    }
}
```

Because the data prop has an underscore `_` in its name, its private and has to be accesses with `this.$data._chart` instead only `this._chart` .


`ctx.this` does not make sense at all. Because your ctx is the chart context. And it does not have the all your vue instance props.

Just console.log your ctx. It should contain all information you need.

---

Otherwhise check out the docs for plugin development or check out stackoverflow, as this is not really related to `vue-chartjs`, more to general chartjs plugin development.
