### ISSUE TITLE
responsive=true causes chart never to display if parent container is initially hidden

### ISSUE THREAD

**Issue by roncemer** [apertureless/vue-chartjs#372]
### Expected Behavior
Create a chart which is initially hidden (showChart is false).  Start with your line-chart example.
&lt;line-chart v-show="showChart"&gt;&lt;/line-chart&gt;

In the chart component options, set responsive to true and maintainAspectRatio to false.

When showChart is set to true, the chart should show.

### Actual Behavior

Chart does not show.

Change responsive to false, and the chart will show when showChart is set to true, but will not be the full width of the container / canvas.

The initial visibility of the container should not affect whether the chart works.  When the container is made visible, the chart should resize accordingly if responsive is true.

### Environment
- vue.js version: 2.5.16
- vue-chart.js version: 3.3.1
- npm version: 5.6.0

**Comment by apertureless** [comment]
Hey @roncemer 

check out the [docs](http://www.chartjs.org/docs/latest/general/responsive.html) for the responsive options in chart.js 

There is an [important note](http://www.chartjs.org/docs/latest/general/responsive.html#important-note)

>Detecting when the canvas size changes can not be done directly from the CANVAS element. Chart.js uses its parent container to update the canvas render and display sizes. However, this method requires the container to be relatively positioned and dedicated to the chart canvas only. Responsiveness can then be achieved by setting relative values for the container size (example):

---

So this means, if you have `responsive: true` your canvas will resize based on your parent container. If you have `responsive: false` it will have fixed width & height.

You are using in your example code `v-show`. Which is basically `display: none`. So your chart components get mounted & rendered. But because your parent container is set to `display: none` your chart width & height are 0. Because your parent container has no height nor width. 

If you want to show or hide your chart components you should use `v-if` which will properly destroy and remount your component. Because of the proper remount your chart gets rendered while your parent container is visible and has a width and height. And then it can accordingly detect its size.

**Comment by roncemer** [comment]
Yes, it turns out it's just the way Chart.js works.  Basically, you can't have an auto-resizing canvas and expect the chart to re-scale and re-render properly, at least not easily.  I ended up specifying width and height on the canvas(es), and just going with fixed-size charts.  So this is definitely not a bug with vue-chartjs, but simply the way Chart.js works.
