### ISSUE TITLE
Tooltip z-index problem

### ISSUE THREAD

**Issue by dreadful44** [apertureless/vue-chartjs#381]
### Expected Behavior
Can settable tooltip z-index from app. So tooltip can show over the parent layout.

### Actual Behavior
When chart has tiny height, tooltip can't show. Because z-index, tooltip shows inside chart element and is look like cropped image.

[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r54jj1746o)

### Environment
- vue.js version: 2.5.13
- vue-chart.js version: 3.3.1
- npm version: 5.8.0

**Comment by apertureless** [comment]
Hi @dreadful44 

Thanks for the reproduction link.
This is however not a z-index problem. The problem is, because your chart is so small the canvas is small too. And you can not render elements outside of the canvas.

![bildschirmfoto 2018-06-28 um 10 00 47](https://user-images.githubusercontent.com/4975917/42021265-76310a70-7aba-11e8-86a9-b1532968b373.png)

So the canvas is your boundary for rendering things. So the tooltip can not overlap it.
