### ISSUE TITLE
Help with chart that does not update appreciated

### ISSUE THREAD

**Issue by devleaks** [apertureless/vue-chartjs#402]
### Expected Behavior
Live update of chart

### Actual Behavior
Chart remain static with initial set

### Environment
- vue.js version: 2.5.17
- vue-chart.js version: 3.4.0
- npm version: 6.3.0

Hello,

I cloned [vuepoint](https://github.com/mattbrailsford/vuepoint) repo, updated packages to latest versions, it is working.

The live update feature does not work in the version of vuepoint. So I try to add it.
I added a new chart type to live update data based on your demo . I use the reactiveProp version.

When I inspect the vue component with devtools, I see `chartData` prop that changes with my updates but the chart does not update. How can I further debug?

Thanks

P.

**Comment by apertureless** [comment]
Can you please provide a reproduction? (jsfiddle / codepen / sandbox)
Without code it is hard to say where the problem is.

**Comment by devleaks** [comment]
OK. I created a new vue cli (R3) project.
Copied src from vuepoint [repo](https://github.com/mattbrailsford/vuepoint), adjusted a few paths, [got it to compile & work](https://github.com/devleaks/vuepoint-new).

I added `src/components/charts/UpdatePropChart.vue`.
I'm trying to pass `chartData1` defined and live updated in src/App down to
  -> chart-tile (:data="chartdata1") which is a `Tile`
  -> update-prop-chart (:chart-data="localData") which is a plain VueChartJS `Line` with reactiveProp mixin.

In chart-tile, I added a localData data and the following watch that never get triggered:
```
    watch: {
        data: function() {
            this.localData = this.data;
        }
    }
```
So localData never gets copied and transmitted to `update-prop-chart` child.
Why?
I have a similar, simple test case, without the intermediate Tile and there it works. Here it does not and I cannot understand what I'm doing wrong.
P.

**Comment by jonasohrn** [comment]
I have similar problem.
I noticed that the watcher added by the 'reactiveProp' mixin is not triggered unless any root property of the watched property "chartData" is changed. So not so useful when the actual data value changes.
If I then copied that watcher and add deep: true to watcher options, I instead get problems with Vue warnings "[Vue warn]: You may have an infinite update loop in watcher with expression "chartData""
It seems that we get problem because some deep nested data in the shared chartData is mutated somehow by chart.update() making Vue watcher triggering unwanted(ghost) changes constantly.
The only solution was to watch the chartData.datasets[0].data array separately (deep not needed) and call chart.update() by first makeing a copy of that data array into this.dataArray and watch that.

**Comment by tripflex** [comment]
+1 can confirm this is an issue as well!

**Comment by JStrebeyko** [comment]
The feature discussed here is awesome and I love it being implemented here.

Unfortunately, on my end changes in `mixins.reactiveProp` do not update charts, for complex data structures at least. Followed the same steps as @jonasohrn, and ended up with the same results, except I don't quite get the solution:
>... was to watch the chartData.datasets[0].data array separately (deep not needed) and call chart.update() by first makeing a copy of that data array into this.dataArray and watch that.

Question 1: Could you please share the watcher code for this part or perhaps elaborate? My understanding is that you are watching a property, calling update on change and honestly, next I get lost with this copying and watching something else. 

Question 2: Does this solution also deal with situations when we do not know exactly which part of data object passed as `chartData` is changing? It feels it is rigged to deal with a particular, known-ahead-of-time fraction of possible model, but I might be wrong.
