### ISSUE TITLE
working with dynamic data

### ISSUE THREAD

**Issue by robertnicjoo** [apertureless/vue-chartjs#411]
Hi,

> This is my first attempt with this package and i'm completely newbie with it.

### What I want to do
Get number of my projects in chart (simple act)

I've tried some samples from this package docs, pusher blog etc. no luck so far.

### What I have
Vue.js in Laravel and my component is like:

```
<canvas id="myChart" height="100"></canvas>

<script>
import Chart from 'chart.js';
import VueCharts from 'vue-chartjs';
    export default {
......
</script>
```
That's all I have (clean it after unsuccessful attempts) so basically I only have charjs loaded to my component and made canvas in my template for it. I also have this route to get data that I want

`axios.get("/api/projects").then....`

### Question

Can anyone help me to understand how to get my results in chart please?

### Environment
- vue.js version: ^2.5.7
- vue-chart.js version: ^3.4.0
- npm version: 5.6.0

**Comment by apertureless** [comment]
Hi @robertnicjoo 

well, have to took a look into the [vue-chartjs docs](https://vue-chartjs.org/#/) ?

Your chart component looks quite wrong. Because you don't need to import Chart.js and you do not have to add a template tag with a canvas. This will break everything, because you `extend` your own chart component with the vue-chartjs one. However Vue can not merge templates. If you add a template you will end up with an emtpy component.

There are also plenty of [resources](https://vue-chartjs.org/#/home?id=resources) and tutorials how to use vue-chartjs with apis.
