### ISSUE TITLE
Reactive Props dont work , need deep option

### ISSUE THREAD

**Issue by MrJmpl3** [apertureless/vue-chartjs#416]
### Expected Behavior

Reactive Props in Vuejs ChartJs

### Actual Behavior

The watchers dont work in the props.
I tried some things , i found the solution , add deep option in the watchers.

PD: Warning , with the infinite loop, I only use this.$data._chart.update(); without mixins

### Environment
- vue.js version: 2.5.17
- vue-chart.js version: 3.4.0
- npm version: 6.4.1

**Comment by MrJmpl3** [comment]
Posible Solution:

Without Infinite Loop..

I used Typescript ... e.e

```
import { Component, Prop, Watch } from 'nuxt-property-decorator';
import { Bar } from 'vue-chartjs';
import { mixins } from 'vue-class-component';

@Component({})
export default class ChartComprobantesPorMes extends mixins(Bar) {
  public chartData: object;

  @Prop(Object)
  public data: object;

  @Prop(Object)
  public options: object;

  @Watch('data', { deep: true })
  public onDataChanged() {
    this.chartData = this.data;
    this.$data._chart.destroy();
    this.renderChart(this.chartData, this.options);
  }

  public mounted() {
    this.renderChart(this.chartData, this.options);
  }
}
```

**Comment by apertureless** [comment]
¯\_(ツ)_/¯

> The watchers dont work in the props.

Well this is not true. The watcher /  mixin works quite fine.
There are however edge cases depending on how you get your data (local data / api reuqests) and how you set the new data. Which is mostly resulted in the fact, that chart.js per default is not made for reactive data. And there are many edge cases and use cases how people fill their data.

Adding `deep: true` to the mixin can result in very high memory consumtion up to the case where the browser freezes, because the chart.js object can be quite huge.
