### ISSUE TITLE
Animation onProgress doesn't fire until hover

### ISSUE THREAD

**Issue by RBrNx** [apertureless/vue-chartjs#417]
I have an issue that is perhaps to do with either ChartJS or Vue-ChartJS, I am unsure which so I chose to create an issue here.

I have a Popup component with several Bar Chart components as children. This popup component uses `v-show` to become visible when a button is clicked. The Bar Chart components use the `onProgress` callback during animation to render some extra text on the chart.

### Expected Behavior
When the popup appears, the Bar Charts are visible with the extra text shown.

### Actual Behavior
When the popup appears, the Bar Charts are visible but the extra text is not drawn until I hover over the chart. It seems like the `onProgress` callback does not get fired since the Chart is not visible.

You can see this problem in this [CodeSandbox](https://codesandbox.io/s/r71q4qwv8m). The labels are not shown when the popup is made visible, but when the chart is hovered. If the Popup is shown by default (i.e without a button click) then the labels render correctly.

### Environment
- vue.js version: 2.5.16
- vue-chart.js version: 3.3.2
- npm version: 5.6.0

**Comment by RBrNx** [comment]
I have tried to recreate this issue in plain ChartJS, but the problem does not appear as you can see [here](https://codesandbox.io/s/q8jq99974w).

So perhaps it is to do with how the Chart is handled by Vue when it is not shown be default?

**Comment by apertureless** [comment]
Hi @RBrNx 
sorry for the late reply. I was sick the last weeks 🤧 

I guess your problem is the `v-show`. Because `v-show` is basically just a `display: none`. So if the page loads your components inside the `v-show` will be created and mounted.

So if I load the codesandbox example, your `onProgress` callback is triggered initially. Because the charts are mounted, even they are not visible.

Then if I click the button to toggle them, they show up. However the callback does not get triggered, because nothing really happens beside the `display: none` -> `display: block`.

If you change your code and swap the `v-show` with a `v-if` it should work as expected (if I understand it correctly).

Because `v-if` really mounts and destroys components, the `onProgress` callback will be fired if you toggle the button and you also get the animation.

**Comment by RBrNx** [comment]
Thanks for the reply @apertureless, no worries about being sick!

Yeah I ended up changing to `v-if` and got it to work correctly, so thank you for your help!
