### ISSUE TITLE
generateLegend missing in 3.4.0 release code...?

### ISSUE THREAD

**Issue by jester12345** [apertureless/vue-chartjs#441]
I downloaded 3.4.0 from the latest release (https://github.com/apertureless/vue-chartjs/releases), using the Zip option. Unless I'm misunderstanding something, the generateLegend() wrapper function is missing from dist/vue-chartjs.js and dist/vue-chartjs.min.js.

The version you get distributed in node_modules has it.

**Comment by apertureless** [comment]
Hi @jester12345 
yeah this is because the releases are handled by `standard-version` with automatic changelog generation and tagging. However I forgot to commit the `dist` folder before releasing. 

Which is not important for the npm release but github is generating the zip from the commit which got the tag.

So for this release you need to go over the traditional `Download & Clone`

![bildschirmfoto 2018-11-20 um 10 02 27](https://user-images.githubusercontent.com/4975917/48762472-69990980-ecab-11e8-989c-c720b86c7e42.png)
