### ISSUE TITLE
https://vue-chartjs.org provides zero documentation on configuration options

### ISSUE THREAD

**Issue by jedrekdomanski** [apertureless/vue-chartjs#442]
### Expected Behavior
https://vue-chartjs.org provides zero documentation on configuration options, like barThickness, etc. Should I assume that I should be looking at charts.js for more configuration options?

### Environment
- vue.js version: <version here>
- vue-chart.js version: <version here>
- npm version: <version here>

**Comment by apertureless** [comment]
Hello @jedrekdomanski 

yep thats true! The reason for this is, that the documentation is *only* covering topics *specific* to `vue-chartjs`. 

It would be too much efford to maintain the documentation for chart.js, too. Because it would always be behind if something changes in core chart.js. 

So for anything `chart.js` specific you should head over to the [chart.js](http://chartjs.org) docs. Their docs are pretty neat and explaining all the different options.
