### ISSUE TITLE
Questions: Update chart options without new data

### ISSUE THREAD

**Issue by akhchan99** [apertureless/vue-chartjs#449]
I created a time series line chart that query data from an API that get data within a 4 hours period.
Therefore I set the time.min / time.max as the boundary, as the data point is not continuous.
And I added buttons to move forward/backward in 4 hours increment.

If within the 4 hrs period, there're data in it, everything is fine, the x-axes boundary will update and new data shown on the chart.  But if the 4 hrs period doesn't have any data.  the x-axes boundary doesn't change even thought the time.min / time.max options are set.

i tried to manually issue this.$data._chart.update() and it still won't refresh the chart with the new options value for the min/max time range on x-axes.

**Comment by akhchan99** [comment]
https://codepen.io/anon/pen/dwdRvz

on the updateChart method, I update the chart data and chart options, but only the chart data are updated, not the chart options.

what I intended to do is fixed the start/end time of the time series chart regardless of the range of data in the chartdata.

**Comment by apertureless** [comment]
@akhchan99 

You will need to properly destroy and re-render the chart.

The problem here is that `_chart.update()` which is the Chart.js update method *only* updates the charts datasets. Not the options.

There is no way in Chart.js AFAIK to update the `options` object.
Thus you will need to destroy and re-render it if you change the options.

```js

this.$data._chart.destroy()
this.renderChart(this.chartData, this.options);
```
