### ISSUE TITLE
Confusion about documentation for browser usage

### ISSUE THREAD

**Issue by dustinmichels** [apertureless/vue-chartjs#450]
The documentation [states](https://vue-chartjs.org/guide/#vue-single-file-components):

> Most examples in the docs are based on javascript files and not .vue files. This is because you mostly will only need the <script> block. You can however use .vue files as well.

However all the examples seem to be written in the webpack / .vue style, and the only example I can find which uses the browser-based script tag style is [this codepen](https://codepen.io/apertureless/pen/zEvvWM).

Am I missing something?

**Comment by dustinmichels** [comment]
Specifically I am looking to [update a chart](https://vue-chartjs.org/guide/#updating-charts) created in the same way as that codepen example, but this does not appear to be documented anywhere?

**Comment by apertureless** [comment]
Hi @dustinmichels 

yes, the examples are mostly for Webpack or other build system users. Either as single javascript files or vue single file components.

The reason is simply because the majority of people are running vue in some kind of build environment. And only a few use it directly in the browser.

Another reason is, that nothing really changes for browser users. And the docs are quite valid for them, too. So my question would be, where do you have problems? Does the object destruction / import is confusing you?

There is a small example in the readme:

https://github.com/apertureless/vue-chartjs#browser

As you see it is actually pretty much the same as the webpack examples. The only difference is that you are not importing the objects, either rely on the global `VueChartJs` object.

So instead of 

```js
import { Line } from 'vue-chartjs'

export default {
  extends: Line
} 

```

You have

```js

Vue.component('line-chart', {
  extends: VueChartJs.Line,
})
```

because `VueChartJs` is the global window object containing all (Line, Bar, mixins) components.

You could also do this:

```js

const { Line } = VueChartJs
 
Vue.component('line-chart', {
  extends: Line
})
```

However object destructing is not available in every (old) browser.  So I did not include it in the readme.


Btw. if you were using webpack you could also do this:


```js
import VueChartJs from 'vue-chartjs'

export default {
  extends: VueChartJs.Line
} 

```
 Without importing the named export directly.

If you take a look at the [index.js](https://github.com/apertureless/vue-chartjs/blob/develop/src/index.js#L16-L29) you will see that the VueChartJs object is containing everything.

You can access all components either over destructing `const { x } = y` or the dot notiation for objects. `objectA.ObjectB`

So if you want to access the reactive mixins you can simply access them over `VueChartJs.mixins.reactiveProp`


```js
Vue.component('line-chart', {
  extends: VueChartJs.Line,
  mixins: [VueChartJs.mixins.reactiveProp]
})
```

**Comment by apertureless** [comment]
Well, it depends on how you **want** to pass the data.

In case of reuseability, you should pass them as props.


```js
Vue.component('line-chart', {
  name: 'MyLineChart',
  extends: VueChartJs.Line,
  mixins: [VueChartJs.mixins.reactiveProp],
  props: ['options'],
  mounted () {
    this.renderChart(this.chartData, this.options)
  }
})
```

And then somewhere where you want to use it

```html

<MyLineChart :chart-data="dataObject" :options="optionsObject" /> 
```
