### ISSUE TITLE
Documentation or name change request for reactiveProp mixin

### ISSUE THREAD

**Issue by swirlingsand** [apertureless/vue-chartjs#457]
### Expected Behavior

The prop name should have a clear reference point to the variable for chart data.
In the context of using reactiveProp mixin

ie `chart_data == chart_data`

In a component:
```
    <line_chart :chart_data ="datacollection"
                :options="options">
    </line_chart>
```

Then in line_chart
```
this.renderChart(this.chart_data, this.options)
```
I understand not mutating props directly,
two ideas:
this.renderChart() handles any local stuff as needed,
or if for some reason that doesn't work, 
maybe the convention chart_data and chart_data_prop.

This is way too confusing:
```
chartData == chart-data
```
I haven't found it in the docs yet, but that's what it appears to be the behavior of the sample data. 

### Actual Behavior

In a component:
```
    <line_chart :chart-data="datacollection"
                :options="options">
    </line_chart>
```

And then in line_chart:
```
props: ['options'] ...
this.renderChart(this.chartData, this.options)
```

### Environment
- vue.js version: 2.5.16
- vue-chart.js version: 3.4.0
- npm version: 5.6.0

**Comment by apertureless** [comment]
Hi @swirlingsand 
thanks for your request.

However I don't really understand the underlying issue here.

Are you confused by the `camelCase` to `kebab-cased` notation?
That's actually standard Vue behaviour.

If you declare props or components with `camelCase` they need to be written in `kebab-case`, because html attributes are case-insensetive [vue docs](https://vuejs.org/v2/guide/components-props.html#Prop-Casing-camelCase-vs-kebab-case)

Component names however can be resolved in both ways.

So if you declare your vue component:

```html

Vue.component('blog-post', {})

```

You can use it either way:

```html
<template>
	<div>
		<blog-post></blog-post> //this is valid
        <BlogPost/> // CamelCase + Self-Closing is valid too.
	</div>
</template>

```

I see that you are using `snake_case` for your component and variable names. So I guess you are coming from an another language. Becasue snake case is highly uncommon in the javascript & vue world.
