### ISSUE TITLE
Chart doesn't render when inside sub-component

### ISSUE THREAD

**Issue by moso** [apertureless/vue-chartjs#467]
This might be Vue-related, Nuxt-related, or even axios-related. However...

A little explaination:
- `~/components/chartjs/LineChart.vue` imports `{ Line } from 'vue-chartjs'` and contains options.
- `~/components/ChartTypeOne.vue` imports `~/components/chartjs/LineChart.vue` and contains all the necessary markup for `<line-chart>`, plus a `Promise.all()` to grab 4 types of data from an api.
- `~/pages/index.vue` then imports `~/components/ChartTypeOne.vue`.

If I pull all data from `ChartTypeOne` into `~/pages/index.vue`, it works. But then it's much less reusable, and my index file is full of a ton of data. Plus I'd like to make `ChartTypeTwo`, `ChartTypeThree`, etc, etc. with the same recipe.

### Expected Behavior
For `<chart-type-one />` to actually render data.

### Actual Behavior
Chart lines renders, along with the axis-labels, font-colors, etc, that I've defined in `~/components/chartjs/LineChart.vue`, but no data is being put into the chart.

Is it because I can't go deeper than one component?

### Environment
- vue.js version: 2.5.22
- vue-chart.js version: 3.4.0
- npm version: 6.6.0

**Comment by apertureless** [comment]
Not really sure whats the issue here? You sureley can go deeper than one component if you pass in the data.

However If you are working with APIs you have to make sure, that your chart component is rendered only if the fetching of your data is finished.

https://vue-chartjs.org/guide/#chart-with-api-data

If thats not the issue, please provide a minimal reproduction.

**Comment by moso** [comment]
I figured it out by tampering with it for a few days.

If anyone has the same issue, ping me and I'll provide a solution that worked for me.
