### ISSUE TITLE
Help with labels barchart

### ISSUE THREAD

**Issue by mhbsmatheus** [apertureless/vue-chartjs#468]
### Actual Behavior
![grafico_barras](https://user-images.githubusercontent.com/45985480/51933434-73946280-23e8-11e9-86ba-6724636065a6.png)

I have a bar chart like you guys can see, I'm having some problems to click/hover the values close to the x axis. 

Each label has some value on it, but I can't hover or click on the ones with small values because is to close to the x axis.

Any Ideas to hover/click on these itens are welcome.

My tooltip function for the labels:
`callbacks: {
  label: function (tooltipItem, data) {
    this.ind = tooltipItem.index;
    var label = 'Repassado: ' + currencyFormatter.format(tooltipItem.yLabel, { code: 'BRL' });
    return label;
  }
}`

### Environment
- vue.js version: 2.5.2
- vue-chart.js version: 3.3.2
- npm version: 5.6.0

**Comment by apertureless** [comment]
Hey @mhbsmatheus 

please check out the issues on [Chart.js](https://github.com/chartjs/Chart.js) directly, or on StackOverflow.

Because your issue is not really related to `vue-chartjs`, more to the configuration of chart.js

This issue might help you: https://github.com/chartjs/Chart.js/issues/2959
