### ISSUE TITLE
Destroy chart in beforeDestroy

### ISSUE THREAD

**Issue by alc32** [apertureless/vue-chartjs#476]
### Expected Behavior
Destroy chart when parent component is destroyed

### Actual Behavior
Chart is not destroyed

[Codepen](https://codepen.io/alc32/pen/aXxoJv)

### Environment
- vue.js version: 2.6.6
- vue-chart.js version: 3.4.0

**Comment by apertureless** [comment]
Like you see in the code https://github.com/apertureless/vue-chartjs/blob/develop/src/BaseCharts.js#L82-L86

the chart instance gets destroyed and cleaned up using the Chart.js [destroy()](https://www.chartjs.org/docs/latest/developers/api.html?h=destroy) method

The docs say: 

> Use this to destroy any chart instances that are created. This will clean up any references stored to the chart object within Chart.js, along with any associated event listeners attached by Chart.js. This must be called before the canvas is reused for a new chart.

Which imo does not mean, that the instance object will be null. 
But the references are cleared. 

This works btw. because in the early version of `vue-chartjs` it wasn't destroyed and you had weird overlays if you re-rendering it with different data.
