### ISSUE TITLE
The simplest custom watcher causes console errors [Vue warn] regarding infinite loop

### ISSUE THREAD

**Issue by JStrebeyko** [apertureless/vue-chartjs#487]
### Expected Behavior

Calling `this.renderChart(this.data, this.options)` or `this.$data._chart.update()` should not bring about risk of and console error(s) regarding infinite loops:

>[Vue warn]: You may have an infinite update loop in watcher with expression "data"

### Actual Behavior

1. Create a custom component importing, say, `{ Line } from 'vue-chartjs';`;
2. Create a button clicking upon which changes, say, labels for the chart data object.
3. Realize that `mixins.reactiveProp` does not penetrate data object deeply enough to reach the `labels` property, which is usually the use-case, and that using it would require to change a prop name from `:data` to `:chart-data` of your already widely used component.
4. Create a simple custom watcher instead, whether it be with `this.renderChart(this.data, this.options)` or `this.$data._chart.update()` callbacks to watch over `data` / `chartData` property, [as per the docs](https://vue-chartjs.org/guide/#own-watcher).

On my end, doing so produces errors in the console, with that the `this.renderChart(this.data, this.options)` creates only one, while `this.$data._chart.update()` seems to _actually_ be producing an infinite loop, as the errors are being thrown and stacking circa every second.

### Environment
- vue.js version: `^2.5.21`
- vue-chart.js version: `3.4.0`
- npm version: `5.6.0`

**NOTE:** I think that the project is awesome, loving it. Keep up the good work! :) :beers:

**Comment by apertureless** [comment]
Can you please provide a reproduction? Codesandbox / Codepen whatever? 
Hard to say without seeing the code.

**Comment by JStrebeyko** [comment]
Thanks for swift reply, here is [the example](https://codesandbox.io/s/8zr429x532). Am I missing something?

**Comment by jonasohrn** [comment]
Related to issue #402
This is because of the combination of:
1. vue-chartjs passes the chart data Object directly down to chartjs
2. if we mutate this same chart data Object without calling _chart.update(), then the model inside chartjs will be out of sync.
If we mutate the same chart data Object then we must either manually call update() or make sure a watcher is doing it for us. The one supplied as 'reactiveProps' mixin is only watching on top level attribute changes, not for example data array.
If we watch using Vue's deep mode (like the Codepen example above), then the watcher will trigger in an infinite loop due to chartjs is mutating/changing some metadata deep inside the chart data Object (for popup stuff I guess).

This (current) implementation puts a big responsibility on the user of vue-charts components.
So I would suggest passing a deep cloned copy instead to chartjs, which we can watch deep:true and trigger an update (or re-create if needed - new dataset).

**Comment by JStrebeyko** [comment]
Any chance of having the [the example](https://codesandbox.io/s/8zr429x532) modified so it works with no warnings? I  want to become a responsible vue-chartjs user, but need some guidence in reactive data implementation. Thanks in advance!

**Comment by rafilurie** [comment]
Is there an answer to this question? I am having the same problem
