### ISSUE TITLE
Stepped line middle

### ISSUE THREAD

**Issue by StupidHardLearner** [apertureless/vue-chartjs#494]
Adding stepped line middle doesnt work, stepped line values are:

- Default (false)
- True (Before)
- Before
- After
- Middle

Every one of them works but middle, here is an example:

https://codepen.io/anon/pen/drQpYj

**Comment by apertureless** [comment]
Hi @StupidHardLearner 

thanks for the issue.
However, this is only a wrapper for [Chart.js](https://github.com/chartjs/chart.js). 

And as this issue is not related to vue nor vue-chartjs directly, you should try to create an issue in the core [Chart.js](https://github.com/chartjs/chart.js) repo.

As I cannot fix this issue, if there is any in the options passing or the `steppedLine` option.
