### ISSUE TITLE
How to change Chartjs type dynamically

### ISSUE THREAD

**Issue by essivision** [apertureless/vue-chartjs#533]
### Expected Behavior
I wanna to define a vue component that include `vue-chartjs`. I want to define prop as `chart-type` that can be Line, Bar, etc like below code. In extend property I just add one chart type. What should I do? Do yo have any alternative solutions?

```
<my-chart chart-type="Line" :chart-data="datacollection" :option="options"></my-chart>
```
Thanks

### Environment
- vue.js version: 2.5.*
- vue-chart.js version: 3.4.2
- npm version: 6.4.1

**Comment by apertureless** [comment]
it is not possible.

**Comment by essivision** [comment]
it's very bad. Why?

**Comment by apertureless** [comment]
Well, it is not very bad. 

It is not possible because of how the whole architecture of vue-chartjs is.
It is based on a component structure. Each chart type is a component which you extend in your own component.

Thus it is not possible to "dynamically" change the chart type. 

If you want to achieve this, you could make a wrapper component which holds your own LineChart, BarChart, etc components and swap them out, with dynamic components if `v-if` based on the type prop.

But in my eyes it does not make sense, because you will have very deeply nested components.

In general it does not make much sense to swap chart types. Because chart types are based on your data. You can not represent a pie chart as a line chart. Because you are missing the time based data for your x axis.

If you want to achieve this, you could use just `chart.js` without `vue-chartjs` and write your own components. 

There is also: https://github.com/hchstera/vue-charts 

Which, however, seems to be dead.

**Comment by LeeLenaleee** [comment]
This is possible to do, you just have to go into the chart objects config and change the type and then call the update on the chart. That should change the chart.
`
<script>
import { Line, mixins } from 'vue-chartjs';
const { reactiveProp } = mixins;

export default {
  extends: Line,
  name: "LineChart",
  mixins: [reactiveProp],
  props: {
    options: { type: Object },
    chartType: { type: String }
  },
  mounted () {
    this.renderChart(this.chartData, this.options);
  },
  watch: {
    options: {
      deep: true,
      handler () {
        this.$data._chart.options = this.options;
        this.updateChart();
      }
    },

    chartType (newVal) {
      this.$data._chart.config.type = newVal;
      this.updateChart()
    }
  },
  methods: {
    updateChart () {
      this.$data._chart.update();
    },
  }
}
</script>
`

**Comment by LeeLenaleee** [comment]
it is possible by changing the chart type in the config object of the chart and then calling the update method on it

```javascript
<script>
import { Line, mixins } from 'vue-chartjs';
const { reactiveProp } = mixins;

export default {
  extends: Line,
  name: "LineChart",
  mixins: [reactiveProp],
  props: {
    options: { type: Object },
    chartType: { type: String }
  },
  mounted () {
    this.renderChart(this.chartData, this.options);
  },
  watch: {
    options: {
      deep: true,
      handler () {
        this.$data._chart.options = this.options;
        this.updateChart();
      }
    },

    chartType (newVal) {
      this.$data._chart.config.type = newVal;
      this.updateChart()
    }
  },
  methods: {
    updateChart () {
      this.$data._chart.update();
    },
  }
}
</script>
```

**Comment by apertureless** [comment]
Yeah but this is not persistent and on a re-render (not sure tho) it might reset.
It's also tricky with dynamic types because not all chart types are compatible between each other.
If you have a line chart you have most likeley periodic data, while in a doughnut chart not.

**Comment by zahid99** [comment]
- 

- 

- 

- 

- 

- 

- 

-
