### ISSUE TITLE
Vue warning when using reactiveData mixin

### ISSUE THREAD

**Issue by giggleloop** [apertureless/vue-chartjs#545]
I'm using a CDN import of the script and everything seems to be working, but I'm getting the following error in the browser console:

`The data property "chartData" is already declared as a prop. Use prop default value instead.`

This only occurs when using the reactiveData mixin (which I will be using).

[JSFiddle of the problem here](https://jsfiddle.net/5c4uy0gh/1/)

### Environment
- vue.js version: 2.6.10
- vue-chart.js version: 3.4.2
- npm version: not used

**Comment by apertureless** [comment]
Hi @giggleloop 

yeah the error occurs, because the mixins are already defining the `chartData` prop / data. 

- So the `reactvePropMixin` will define `chartData` as a prop.
- And `reactiveDataMixin` will define `chartData` as a `data: () => ({})` variable.

And you already have defined it yourself as a prop. Thus you have 3 x chartData . Once as a data variable and twice as a prop. With the same name.

Just remove your own definition of it and remove one of the mixins. You only use one of the mixins at a time. It would also make no sense to use both.
