### ISSUE TITLE
problem in show chart

### ISSUE THREAD

**Issue by sasany11** [apertureless/vue-chartjs#567]
### Expected Behavior
showing chart in all windows enviroment and same internet browsers

### Actual Behavior
it dosent show chart in some users desktop computers with same version of internet browsers like google chrome and it generate "chart.flat() is not a function" error

### Environment
- vue.js version: <2.6.10>
- vue-chart.js version: <3.4.2>
- npm version: <10.14.1>

**Comment by apertureless** [comment]
Well it could be because Chart.js internally somewhere uses `Array.prototype.flat()` Which seems to be not supported IE and Edge. But chrome should be fine: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

However, this is not related to `vue-chartjs`. 
You may checkout chart.js browser support: https://www.chartjs.org/docs/latest/developers/#browser-support
