### ISSUE TITLE
Bug in my chart

### ISSUE THREAD

**Issue by lipecss** [apertureless/vue-chartjs#568]
Someone help me for God's sake. I've looked everywhere but it doesn't fit. I created a SPA. every time I search the input it changes the values. In my chart he is giving this bug, of displaying data from the old search, already gave the ** destroy ** within my function of creating it, but does not change anything

my gif : https://media.giphy.com/media/ife73C6juBHs5i6G9j/giphy.gif

```js
methods: {
    async getChannelDatas(name) {
      await axios
      .get(URL)
      .then(async (response) => {
        // Recebe todos os valores dao Mixer Stats
        this.allRecords = response.data.Records.sort((a,b)=>a.UnixTime - b.UnixTime);
        // Sepera apenas a media de usuarios por cada dia num array
        this.setAveragesViwers(response.data.Records);
        // Separa as datas num array
        this.setAllDates(response.data.Records);
      });
      if (this.chart) {
        this.chart.destroy();
      }
      await this.grafico(this.daysRecordChart, this.valuesRecordChart)
    },
    // Função para pegar as medias de viwers num array
    async setAveragesViwers(data) {
      this.valuesRecordChart= await Object.values(data).map(({AverageViewers}) => AverageViewers)
    },
     // Função para pegar as datas de média dos viwers
    async setAllDates(data) {
      this.daysRecordChart = await Object.values(data).map(({Date}) => Date)
    },
    async grafico(label, datas){
      let chart = document.getElementById('myChart')
      await new Chart(chart, {
        type: 'line',
          data: {
            labels: label,
            datasets: [
            {
              label: 'Média de Espectadores',
              borderColor: 'rgba(0,120,215, 0.385)',
              backgroundColor: 'rgba(0,120,215, 0.15)',
              pointHoverRadius: 5,
              pointBackgroundColor: 'rgb(20, 171, 87)',
              pointHoverBackgroundColor: '#DD208A',
              data: datas
            }
          ]
        },
      });
    }
  },```

**Comment by apertureless** [comment]
Well, it does not seem that you are even using `vue-chartjs`. Because you are creating the Charts by yourself. Thats why I am closing the issue.

Your problem will be, that you are not properly clearing up your chart instances.
It is also not a good idea to use `document.getElementById('myChart')`. You should rather use Vue.js `ref` attribute if you want to access something in the dom.

You are also checking if there is `this.chart` and destroying it

```js
if (this.chart) {
  this.chart.destroy();
}
```

But you are never setting your variable.

```js
await new Chart(chart, {....})
```

So, whats happending is, you are checking if `this.chart` is there. It may be, so you are destroying the chart instance. But then you are creating a new chart instance with `await new Chart`. But you are not saving it. 

So if `getChannelDatas` gets called again, it check for `this.chart`, but as it was destroyed in the all before and not reassigned, nothing happens. And then you call again `await new Chart` and you have two chart instances running.
