### ISSUE TITLE
With 'maintainAspectRatio' to false, the graph does not display

### ISSUE THREAD

**Issue by Silverspur** [apertureless/vue-chartjs#580]
Code:
```
<b-card>
    <b-card-body>
        <div>
            <div style="position: relative; height:500px; width:100%;">
                <MyGraph /> <-- this being exactly the vue-chartjs/src/examples/LineExample.js
            </div>
        </div>
    </b-card-body>
</b-card>
```
### Expected Behavior
A graph should show.

### Actual Behavior
Nothing shows.

If switching `maintainAspectRatio` to `true`, the graph shows with an expected ratio of 1, but overflowing out of the bottom of the card.

If furthermore adding 'aspectRatio' property, setting it to something else than 1 (greater or lower), there is no additional effect, the ratio stays at 1.

### Environment
- vue.js version: 2.6.10
- vue-chart.js version: 3.4.2
- npm version: 3.5.2

**Comment by Silverspur** [comment]
My mistake was setting dimensionning styles on my own enclosing div instead of using the `styles` prop to directly style the integrating enclosing div (which I did not know existed before looking at the code).

Playing around with the `styles` prop may thus also solve #576

**Comment by apertureless** [comment]
Check the offical chart.js documentation on responsive behaviour:
https://www.chartjs.org/docs/latest/general/responsive.html

You can also use the `styles` prop to inject dynamic styles.

Otherwise, you need to add a class to your chart component and set some attributes:

```
.wrapper {
  position: relative;
  height: 100%;
  width: 100%;
}
```

Then you can change the width and height of your outer div and the chart will be responsive:

https://codepen.io/apertureless/pen/jZOBeV
