### ISSUE TITLE
Chart does not update on this.$data._chart.update()

### ISSUE THREAD

**Issue by alexeigs** [apertureless/vue-chartjs#582]
### Expected Behavior
Chart should update on `this.$data._chart.update()`

### Actual Behavior
Chart does not update.

Am I missing something? `dataPoints` is reactive and receives new values which the watcher successfully spots and trigger `this.$data._chart.update()` but nothing happens.

```
<script lang="ts">
  import { Component, Mixins, Prop, Watch } from 'vue-property-decorator'
  import { Line } from 'vue-chartjs'
  import { ChartOptions } from 'chart.js'

  @Component({
    components: {}
  })
  export default class ChartLineNonReactive extends Mixins(Line) {
    @Prop({ default: () => [] }) dataPoints!: number[]
    @Prop() scaleMin!: number
    @Prop() scaleMax!: number
    @Prop() reverse?: boolean

    $refs!: {
      canvas: any
    }

    gradient: CanvasGradient | null = null

    get chartData() {
      return {
        labels: this.dataPoints.map((d, i) => i.toString()),
        datasets: [
          {
            data: this.dataPoints,
            backgroundColor: 'transparent',
            borderWidth: 4,
            borderColor: this.gradient!,
            pointBorderWidth: 2
          }
        ]
      }
    }

    get options(): ChartOptions {
      return {
        responsive: true,
        maintainAspectRatio: false,
        layout: { padding: 10 },
        legend: { display: false },
        scales: {
          display: false,
          xAxes: [{
            display: false,
            ticks: {}
          }],
          yAxes:
            [{
              ticks: {
                min: this.scaleMin,
                max: this.scaleMax
              },
              display: false
            }]
        }
      }
    }

    mounted() {
      this.gradient = this.$refs.canvas.getContext('2d').createLinearGradient(0, 0, 0, this.$refs.canvas.height)

      const positive = '#4CD287'
      const warning = '#FFBE60'
      const negative = '#FF8062'

      this.gradient!.addColorStop(this.reverse ? 0 : 1, negative)
      this.gradient!.addColorStop(0.5, warning)
      this.gradient!.addColorStop(this.reverse ? 1 : 0, positive)

      this.renderChart(
        this.chartData,
        this.options
      )
    }

    @Watch('chartData')
    changed(newVal: any, oldVal: any) {
      this.$data._chart.update()
    }
  }
</script>
```

**Comment by apertureless** [comment]
You define a prop `dataPoints` but you never added a watcher for `dataPoints`

**Comment by alexeigs** [comment]
@apertureless `chartData` as a computed property reacts to changes of dataPoints. I watch `chartData` which, to reconfirm, successfully releases a new value each time `dataPoints` is changing. Also the watcher reacts to the changing value of `chartData` (new values both console logged in the chartData-getter and the watcher), just the call of `this.$data._chart.update()` does not have any effect. Any idea what else it could be?

**Comment by apertureless** [comment]
This is indeed weird.

Can you check if instead of calling `update()` calling `this.renderChart(this.chartData,this.options)` solves this?

How are you getting your data? Are you using an api?

**Comment by alexeigs** [comment]
@apertureless Yes, `renderChart` instead of `update` works. Obviously the whole chart gets rerendered now but that is not a big issue in my case. Still it would be interesting to figure out what's going wrong here.

Exactly, I trigger a new fetch which now has changed (or new) values which get injected via props. Everything else works like expected like the reactive getter (`get chartData`).

**Comment by alexeigs** [comment]
@apertureless Any idea what could cause that _bug_ and how I may nail it down?

**Comment by alexeigs** [comment]
@apertureless I would highly appreciate some support on this. While I got very familiar with lots of stuff around these charts, I still haven't solved that problem. Would be great to have a way to update charts without them fully re-render each time.

**Comment by apertureless** [comment]
Hm thats indeed very weird. 
Most of the time there are problems around API calls, because they are async and chart.js will render the chart without proper data. But that will only display an empty chart. But not in your case...

You should maybe check the data after the watcher triggers. Maybe it is incomplete because of the async call? 

You could try a `setTimeout()` before the `update()` call. 

I am not good in TS but I guess ´get chartData()` is the equivalent of a computed property? Maybe chart.js having problems with that.

Can't give you much help here sorry. 

`this.$data._chart.update()` should actually re-render the chart: https://www.chartjs.org/docs/latest/developers/api.html#updateconfig

Not sure why this is not working.

**Comment by alexeigs** [comment]
@apertureless Confirming the status quo:

```
  onChartDataChanged() {
    // doesn't work
    this.$data._chart.update()
    
    // doesn't work
    setTimeout(() => this.$data._chart.update(), 300)

    // works
    this.renderChart(this.chartData, this.options)
  }
```

Also it says `update()` is depreciated, although I don't think that's the reason for it not to work.

The data doesn't change asynchronously, it is really just a chart option that changes like showing a specific data set (from many that are shown) or not. There are also no TS-related issue, that code runs the same as in JS. Also everything else works fine and I have quite many and complex charting. That's really the only issue I face with the library.

**Comment by rick-tibbe** [comment]
I'm having the exact same issue, with almost similar code. `this.chartData` is updating properly in the component, but when I inspect `this.$data._chart.data` I see the data in there is not being updated. A temporary workaround is to disable the animations and just re-render the chart on every update. Not very neat, but it is working.

**Comment by TonBits** [comment]
An update method on the Chart object should be brought down to the vue component similar to renderChart.

I'm sure there are a lot of developers who would rather call update than re-rendering the entire chart when a new data comes in.

In the chartjs pie chart example, 
https://www.chartjs.org/samples/latest/charts/pie.html

it does call update instead of re-rendering the whole chart which makes the transition animation more better than to see the chart re-rendered fully.

I tried the the same same exact thing but to no avail.

this.$data._chart.update()

**Comment by artiomnist** [comment]
I have encountered the same issue. with `this.chartOptions` and my own watcher (as advised by the docs) triggering `this.$data._chart.update()` it does not update the chart. 

My temporary solution was to disable animation and just re-render the chart on every update. Not great, or performant but it is working. 

Any idea when this will be fixed?

**Comment by apertureless** [comment]
I don't think that there will be a fix from my side.
Simply because it's not really a bug inside `vue-chartjs`.

If you add your own watcher and call `this.$data._chart.update()` and it does not update, there is something wrong in your data or with chart.js itself.

`this.$data._chart.update()` is just the internal chart.js update method: https://www.chartjs.org/docs/latest/developers/api.html#updateconfig

So there is nothing I can really do about this.

**Comment by punkt2** [comment]
To change the options, you have to set the new options to the chart object manually in your watcher and then calling update. 
`chart.options = this.options`

```
<script>
import { Scatter, mixins } from 'vue-chartjs'
const { reactiveProp } = mixins

export default {
  extends: Scatter,
  mixins: [reactiveProp],
  props: ['options'],
  mounted() {
    this.renderChart(this.chartData, this.options)
  },
  watch: {
    options() {
      const chart = this.$data._chart
      chart.options = this.options
      chart.update({ duration: 0})
    }
  }
}
</script>
```

**Comment by dsvitnev** [comment]
> To change the options, you have to set the new options to the chart object manually in your watcher and then call update. `chart.options = this.options`
> 
> ```
> <script>
> import { Scatter, mixins } from 'vue-chartjs'
> const { reactiveProp } = mixins
> 
> export default {
>   extends: Scatter,
>   mixins: [reactiveProp],
>   props: ['options'],
>   mounted() {
>     this.renderChart(this.chartData, this.options)
>   },
>   watch: {
>     options() {
>       const chart = this.$data._chart
>       chart.options = this.options
>       chart.update({ duration: 0})
>     }
>   }
> }
> </script>
> ```

Jesus lord, man, your solution saves me, that really works! Thank you!
