### ISSUE TITLE
Rendering of xAxes (doesn't group the same values)

### ISSUE THREAD

**Issue by sdzhurova** [apertureless/vue-chartjs#583]
I am rendering chart connected with temperature data.
I use multiple xAxes for more information. 

On my local environment the days are grouped and the hours as well (image below).
But as soon as I roll out the code live the chart renders differently (image above).
<img width="415" alt="2019-12-03 14_45_18-Untitled - Paint" src="https://user-images.githubusercontent.com/15360847/70057117-de9c6000-15dc-11ea-9595-732daaeb034f.png">

The code and Environment versions are exactly the same.

xAxes time:
`{
              type: 'time',
              distribution: 'series',
              gridLines: {
                drawOnChartArea: false,
              },
              time: {
                displayFormats: {
                  hour: 'H:mm',
                },
                unit: 'hour',
              },
  },`

xAxes day:
`{
            id: 'xAxis2',
            position: 'top',
            type: 'time',
            distribution: 'series',
            bounds: 'ticks',
            gridLines: {
              drawOnChartArea: true,
            },
            time: {
              unit: 'day',
              displayFormats: {
                day: this.translations.format.day_weekday,
              },
            },
 },`

### Expected Behavior
1. To group the days (a.k.a not to have the same days repeated in the xAxes on the top).
2. To have the step for the hour xAxes on every hour (example: 13:00, 14:00, 15:00, etc.).

### Actual Behavior
1. Date doesn't group so there is multiple times 03.12 (3rd of Dec).
2. The hours are automatically calculated how to render.

### Environment
- vue.js version: ^2.5.2
- vue-chart.js version: ^3.5.0
- npm version: >= 4.0.0

**Comment by apertureless** [comment]
Hey @sdzhurova 

well, it is hard to debug, without seeing any code or have a reproduction example.
So please provide at least some code of your components.

Please keep in mind, that if you are using an API **you** have to make sure, the data is loaded, **before** your chart gets rendered. Because otherwise you pass in incomplete datasets to chart.js.

---

Also please keep in mind, that if you are using the `reactiveMixin` your `options` are not reactive and you have to keep them in a options variable.

The reason is, that the mixin is calling either `update()` which is a chartjs internal function or it rerenders with parameters: `this.renderChart(this.chartData, this.options)`

This means, if you pass in your options direclty into the `renderChart()` method, they would get overwritten.

**This would not work**

```js
this.renderChart(this.chartData, { responsive: true, ...otherOptions })
```
