### ISSUE TITLE
Wrong height and documentation issues...

### ISSUE THREAD

**Issue by joeyhub** [apertureless/vue-chartjs#589]
No matter what I do it refuses to fit into its containing div and overflows vertically taking up the height of apparently some parent. How is it actually working out how to fit in?

There are also issues in the documentation such as chartData and chartdata. Can I be sure for example the options property really is options and not something like chartOptions?

**Comment by joeyhub** [comment]
The issue is not putting in the options prop. Not sure if the docs are confusing or not there (data can come from data or props and uses mixin but options is implemented very differently with a different naming convention as well).

It's hard to trust them though with the inconsistency in case.

**Comment by apertureless** [comment]
Hey @joeyhub 

It is hard to say what the issue is, without seeing any code. ¯\_(ツ)_/¯
If you see issues in the docs, feel free to make a PR.

---

You can name your variables, however you want! You can name them `chartData`, `chartdata`, `mydata`, `lol` or whatever name you want. The same goes for the `options`. If you feel brave enough you can even pass the object directly into the render function.

```js
this.renderChart({....}, {...})
```

This is totally valid. As `this.renderChart()` expects two arguments:

- An object with the chart data like described in the official chart.js documentation
- An object with options inside it, like described in the official chart.js documentation.


## Exception: 

The **one** exception is, when you are using the `reactiveMixins` helpers. 
The reason is, that these mixins are just boilerplate code. They will create a variable for your data and add a watcher to it to handle the re-rendering

So you make it easier for people, it creates a prop / data variable named `chartData` and adds a watcher to it: https://github.com/apertureless/vue-chartjs/blob/develop/src/mixins/index.js#L78-L84


Now because the chart.js `update()` method does not always work we have to re-render the chart completely in some cases.

See here: https://github.com/apertureless/vue-chartjs/blob/develop/src/mixins/index.js#L62

For this, it is required to call the `this.renderChart()` method with its two arguments. Thats why you need your options to be named `options`.
