### ISSUE TITLE
Emit events not working

### ISSUE THREAD

**Issue by richlove1** [apertureless/vue-chartjs#599]
### Expected Behavior
Expecting the 'chart:render' event to be emitted once the chart is rendered but nothing seems to be happening. Not sure if I am doing something wrong!

**Parent:**
```
temp() {
      console.log("chart rendered....");
}
```

`<PieChart :chartData="chartDataPie"  v-on:chart:render="temp()"/>`

**Pie.vue**
```
export default {
        extends: Pie,
        mixins: [mixins.reactiveProp],
        data: () => ({
        }),
        mounted () {
            this.renderChart(this.chartData, this.chartData.options)
        }
    } 
```

Any ideas? Basically, I'm trying to recognise in the calling component that the chart has finished rendering to reset a flag.

**Comment by apertureless** [comment]
Hey @richlove1 
your code looks okay.

However, two things to keep in mind.


1. The events are only for the mixin. And are **not** life-cycle events. This means the first render of your chart will never emit any event. Because the mixin only triggers after a data change.

2. The `@chart:render=""` event is only emitted if the mixin performs a full re-render cycle of the chart. Which is not always the case. So it is always good to also check for `@chart:update` . I would say most of the time (depending on how you change your data) the `update` event is emitted. Because the mixin mostly tries to use the chartja update() method. So your chart is properly animated if data changes.

**Comment by richlove1** [comment]
Thanks very much for the reply. I did try using the @chart:update method also but saw no event emitted.

Is there a simple/elegant way to emit an event to the calling component that the initial render has been completed? Should I use a watcher on the data in the component rendering the chart, then manually emit a custom event for the parent to listen for? (or is there a hook/event I can listen for in the component rendering the chart?)

**Comment by apertureless** [comment]
Not exactly sure what you mean.
You have your `Pie.vue` component, where you control the initial render.
If you want an event for the very first render, just emit an event after you call `this.renderChart()`

```js
export default {
        extends: Pie,
        mixins: [mixins.reactiveProp],
        data: () => ({
        }),
        mounted () {
            this.renderChart(this.chartData, this.chartData.options)
            this.$emit('chart:rendered')
        }
    } 
```

After your data changes, the mixin should emit the events.

**Comment by richlove1** [comment]
Thanks, that's exactly what I ended up doing.

I'm facing another issue now in that the watcher (from mixin doesn't work), and also if I replicate it manually it doesn't work. In fact, I'm not sure how it can work in its current form because the data  that's changing (in the data array) is nested in the chartData.datasets object. My understanding is that Vue won't observe changes on nested data in a watcher like this?

I've tried setting the watched up manually with the deep=true property set, which now observes changes to the data
