### ISSUE TITLE
Cant get sizing to do anything different at all

### ISSUE THREAD

**Issue by ronnyek** [apertureless/vue-chartjs#616]
### Expected Behavior
Wrapping a chart in a fixed div would set the size for the chart.
LineChart.vue
``` ts
<script lang="ts">
import { Line, mixins } from 'vue-chartjs'
import Component from 'vue-class-component'
import { Prop } from 'vue-property-decorator'
import Vue from 'vue'
const { reactiveProp } = mixins

@Component({
  extends: Line,
  mixins: [reactiveProp]
})
export default class LineChart extends Vue {
  @Prop()
  chartData: any

  @Prop()
  options!: any

  renderChart!: (chartData: any, options: any) => void

  mounted () {
    console.log('using options', this.options)
    this.renderChart(this.chartData, this.options)
  }
}
</script>
```
and consume like so
`<line-chart :chart-data="chartData" :options="options"></line-chart>`

I've tried fiddling with chart options for height/width, 'responsive', 'maintainAspectRatio' etc, and see the options being passed to chartjs.  I've also tried just wrapping a fixed height/width div around the '<line-chart>', and even though div height is set to '400px', chart keeps trying to render at 600. 

What it almost SEEMS like is happening is that even though I'm passing `maintainAspectRatio: false ` its using width as the aspect ratio and rendering as a square chart no matter what I try to do for the height.

I've seen the pen with an example, so I believe it works as expected in places, but totally lost here =(

### Actual Behavior
Nothing I change, anywhere I change it affects height of the chart at all as best I can tell.

### Environment
- vue.js version: 2.6.11
- vue-chart.js version: 3.5.0

**Comment by apertureless** [comment]
Well, not really sure what you are trying to achieve here.
Per default the chart component has a width and height of 400. Which is sadly some legacy code, because in the earlier days you always had to set the width and height for the canvas to properly work.

So you might want to try to set the `:width="null" :height="null"`. There is an issue for that: https://github.com/apertureless/vue-chartjs/issues/503

If you want the chart fully responsive check out the docs: https://www.chartjs.org/docs/latest/general/responsive.html

You have to set the container to `position: realative`. Then it should work and fully adapt.

Here is an example with vue-grid: https://codepen.io/apertureless/pen/jZOBeV

**Comment by zeke8402** [comment]
Hi, I was having the same issue. I can confirm that setting width and height to null on the chart allowed me to manipulate it.

Might I suggest updating the documentation here:
https://vue-chartjs.org/guide/#chart-with-dynamic-styles

The current docs makes no mention of this requirement, and there is no other way to size the charts without this hack.
