### ISSUE TITLE
Tooltip label callback dont work in Nuxt on SSR 

### ISSUE THREAD

**Issue by rustam87** [apertureless/vue-chartjs#634]
I have app in Nuxt (ver 2.13.0)
I have a chart type Doughnut
Chart's optiions 

```
tooltips: {
            callbacks: {
              label: (tooltipItem) => {
                return 'test' + tooltipItem.index
              }
            }
          }
```
Chart has a strange behavior 
When i go to the page with chart on SPA mode, tooltips works fine 
https://i.imgur.com/c4jwk3y.jpg - debug image

When i reload page,  i get  error -  Callbacks.label.call is not a function 
https://i.imgur.com/1gUNf1U.jpg - debug image

As you see, when page generate on server and on client , callbacks.label has differents.
Thanks

### Expected Behavior
tooltip doh't appear with concole error 
Callbacks.label.call is not a function 

### Actual Behavior
i see tooltip

### Environment
- nuxt version: 2.13.0
- vue-chart.js version: 3.5.1
- chart.js version: 2.9.3
- yarn version: 1.22.4

**Comment by maulayyacyber** [comment]
i have same the problem

**Comment by Esensats** [comment]
I have the same (I think) problem. When I use Nuxt 2's `fetch()` hook in my view component my bar chart suddenly stops working. The error being thrown is `TypeError: ({}) is not a function` -> Chart.js:11684 :>> `me.ticks = me.ticks.map(tickOpts.userCallback || tickOpts.callback, this);`

When I use `created()` instead of `fetch()` and fetch data on client side, everything works. But the thing is, I pass the same data to the chart, and the chart is being rendered only after the fetch completed (through a `v-if="isLoaded"`, where `isLoaded` is equal to `true` after the fetch.

`<client-only>` around the chart component doesn't help.
