### ISSUE TITLE
Chart size props not working

### ISSUE THREAD

**Issue by OHR7** [apertureless/vue-chartjs#646]
```
<script>
import { Bar } from 'vue-chartjs'

export default {
  data: () => ({
    chartdata: {
        labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        responsive: true,
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
  }),
  extends: Bar,
  mounted () {
    this.renderChart(this.chartdata, this.options)
  }
}
</script>
 ```

```
<template>
  <div class="container">
    <div class="row">
        <h1>Home</h1>
    </div>
    <bar-chart height="100" width="100"/>
  </div>
</template>
```

### Expected Behavior
chart with this size <bar-chart height="100" width="100"/>

### Actual Behavior
The chart is way bigger than 100px, basically ignores the props,
also if I send styles prop with 100px (like in the docs), the div is in 100px but chart still bigger than 100px and overflows the container div

### Environment
- vue.js version: 2.6.11
- vue-chart.js version: 3.5.1
- chart.js version: 2.9.3
- npm version: 6.14.8

**Comment by welpie21** [comment]
could you maybe try: `:height="250"`? i've also had a similar problem. but with the double dot it fixed it for me at least.. could you maybe try it?

**Comment by peppered** [comment]
I had the same issue. Unfortunately, the solution suggested by @welpie21 is just a synthetic sugar for Vue's `v-bind` and it doesn't related to `chart.js`. The solution would be one of the following:
1. Turn off the responsiveness by setting the `options.responsive: false`
2. While preserving the responsiveness set the `options.maintainAspectRatio: false`

You could find more information from the [official docs](https://www.chartjs.org/docs/latest/general/responsive.html#important-note)

**Comment by AtomSolar** [comment]
I thought I'd add to the pile of issues. I'm having issues making the height work correctly, I'm able to make the container that the component is nested in's height to 400 but the actual chart is 450. I don't know if I'm missing anything but this is super annoying

**Comment by AtomSolar** [comment]
> I thought I'd add to the pile of issues. I'm having issues making the height work correctly, I'm able to make the container that the component is nested in's height to 400 but the actual chart is 450. I don't know if I'm missing anything but this is super annoying

Update the chart has a minimum height... wtf? Can't get it to go smaller than 400px. It'll do for now but I'm likely going to switch entirely

**Comment by apertureless** [comment]
@AtomSolar What exactly are you wanting to achieve? If you want a fix height, set the `:height` prop and disbale the aspectRatio and responsiveness in the options.

https://codepen.io/apertureless/pen/bxJMbj

**Comment by AtomSolar** [comment]
@apertureless 
Awesome good. I'm using a .vue SPC where I don't have the element, how can I do it there?

**Comment by apertureless** [comment]
Which element are you talking about? 
It is basically the same

**Comment by AtomSolar** [comment]
Ah I see, The docs need clarification, as per https://vue-chartjs.org/guide/#vue-single-file-components 
The docs say explicitly not to use a template so in my mind all I had available to me was the single object from that portion of the page and no actual <LineChart /> element. Does that make sense? That is why I said I don't have access to the element, my Chart.vue only contains the return and style portions, not the <xChart /> element :)

**Comment by apertureless** [comment]
Sorry, still don't really understand you. Why does the docs need clarification?
It is still right, whats written there.

1. You create your own chart component.

This component will be extended by the base component. The base component is the one you import from vue-chartjs. You can either use the `extend:` or `mixins:[]` prop. Because both work the same way. This way, your component get access to predefined methods, props etc. all the setup that is required to run chart.js. And also the template with the canvas etc. you dont need to setup anything.

Your component can be a simple js file (chart.js) with just `export default { .... }` or if you have vue-loader you can make a Vue SFC. (chart.vue). In this case it is important to only provide the script and style tags and not the template. Because like any other mixin, vuejs can't merge templates. So if you put a template tag in your chart component, this would overwrite the template in the mixin / extend with the canvas. 

2. Using your component

If you want to use your component, like any other vue component, you just import it and put it into the template of your parent component. (App.vue or where you want to use it). There you'll pass the chart-data, options and other props to your chart component.


And thats the same for single file components, js files or global component registration with 

````
  extends: VueChartJs.Line,
  mounted () {
    this.renderChart({
      labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
      datasets: [
        {
          label: 'Data One',
          backgroundColor: '#f87979',
          data: [40, 39, 10, 40, 39, 80, 40]
        }
      ]
    }, {responsive: true, maintainAspectRatio: false})
  }
```

Like you see, there is also NO template in the global registration.


I guess you mixed up the Chart component template and template of your parent component where you are using the chart component.
