### ISSUE TITLE
Error: Please remove the <template></template> tags from your chart component

### ISSUE THREAD

**Issue by MRR0GERS** [apertureless/vue-chartjs#679]
### Expected Behavior
No error

### Actual Behavior
I have 3 different SFC chart components that are loaded on a page.  The SFCs look almost 1:1 with the example in the documentation on using vue-chartjs in SFCs.  There are no template tags in the SFCs just the script tags.  When I load the view with the chart SFCs I get

`Error: Please remove the <template></template> tags from your chart component. See https://vue-chartjs.org/guide/#vue-single-file-components`

I'm using both the Bar and Pie charts.  They still render but I get the error for each of the SFCs that are loaded.

### Environment
- vue.js version: 2.6.12
- vue-chart.js version: 3.5.1
- chart.js version: 2.9.4
- npm version: 6.4.11

**Comment by MRR0GERS** [comment]
I was able to resolve the issue by changing the immediate property to false in my watcher.

**Comment by apertureless** [comment]
Yeah I'm checking in the renderChart method if the canvas element is present.
If not, the chance is very high, that the user added template tags to their SFCs which overwrite the template from the mixin and removing the canvas.

https://github.com/apertureless/vue-chartjs/blob/develop/src/BaseCharts.js#L72

I guess with `immediate` it will try to render the chart, without the canvas element.

**Comment by soyekeye** [comment]
I still have this same problem

**Comment by newcat** [comment]
Same here when I use a specific setup with computed properties for `chartData` The reason is that the [watcher for `props.chartOptions`](https://github.com/apertureless/vue-chartjs/blob/main/src/BaseCharts.ts#L232-L236) is called before the `onMounted` callback. The watcher handler sees that the chart has not been initialized yet and therefore calls the `chartCreate` function, which in turn calls the `renderChart` function. At this point, the ref to the canvas has not been set, as the `onMounted` callback has also not been called. This leads to the error.

@apertureless it would be nice if you could fix it so the `chartCreate` or `renderChart` functions just fail silently if they are called before `onMounted` (or the watchers check, whether the component has been mounted yet and if that is not the case, they simply don't call their respective handlers).

**Comment by dargmuesli** [comment]
@apertureless could you reopen this issue, please? @newcat described the problem very well :raised_hands:

**Comment by gbaron** [comment]
@newcat could you please provide more information about the "specific setup with computed properties for chartData". Ideally a codepen/repo with reproducible code.
Thanks

**Comment by RobineSavert** [comment]
Any updates on this? Our team runs into the same problem..

**Comment by dangreen** [comment]
@newcat @dargmuesli @RobineSavert Hi. vue-chartjs was refactored in v5, and v4 is no more maintained. Did you have the same issue with vue-chartjs v5?

**Comment by dargmuesli** [comment]
I have not yet faced any issues with v5.

**Comment by RobineSavert** [comment]
> @newcat @dargmuesli @RobineSavert Hi. vue-chartjs was refactored in v5, and v4 is no more maintained. Did you have the same issue with vue-chartjs v5?

I saw later on that we run on vue-chartjs 3.5.1 so I have some major updating to do first. Thanks for the reply!

**Comment by newcat** [comment]
>Hi. vue-chartjs was refactored in v5, and v4 is no more maintained. Did you have the same issue with vue-chartjs v5?

Sorry for the late reply, v5 fixed it, thank you very much!
