### ISSUE TITLE
Chart disappears (height and width set to 0) when responsive is true and chart is dragged

### ISSUE THREAD

**Issue by LovelyAndy** [apertureless/vue-chartjs#728]
### Expected Behavior
The chart is responsive and is able to be dragged around the wrapping component like normal.

### Actual Behavior
**When responsive = true and you drag the chart, it's height and width are set to 0 and the chart disappears.** 

I currently have a [**stackoverflow**](https://stackoverflow.com/questions/70024058/chartjs-charts-disappearing-when-dragged-and-responsive-option-is-true-why-is-t?noredirect=1#comment123784328_70024058) post on this and have recreated the issue in [**CodeSandbox**](https://codesandbox.io/s/draggable-charts-8uck7?file=/src/components/Chart2.vue), but I have yet to solve this issue. 

This definitely seems to be a ChartJS error, because as long as the chart is not responsive, it is able to be dragged. I have a toggle in the CodeSandbox for responsiveness so you can test it yourself. My only idea for a work around is that when you click to drag, there would be some hidden toggle checkbox for responsiveness and would allow you to drag and when it's let go you it reverts back to responsive. That's just a lot of potential code that I would like to avoid if there is a simple fix. 

If anyone has any idea or advice I would really appreciate it. 

### Environment
- vue.js version: <Vue3>
- vue-chart.js version: <2.9.4>
- chart.js version: <3.6.0>
- npm version: <6.14.14>
 
![chartsGif](https://user-images.githubusercontent.com/68723584/142484482-04de97b6-92e5-43d1-ba13-245285357961.gif)

**Comment by apertureless** [comment]
This will be related to the canvas element. If you take a look at the documentation https://www.chartjs.org/docs/latest/configuration/responsive.html so will get some additional information.

I guess whats happening is, that the canvas element will reset its width and height to 0 because of the drag. It is kinda cut off from the DOM and then inserted at another place, however then loosing the width and height attribute.

Because in the time of the drag the width and height are 0. (It is cut out of the DOM).

However this is not vue-chartjs related. And you btw. also not using vue-chartjs.

**Comment by LovelyAndy** [comment]
@apertureless Thank you for the response. I brought this up on Chartjs as well and they introduced a fix in their newest release.
I am using Vue-Chart-3 which is a rewrite of vue-chartjs which allows for typescript and composition API, so I figured this was also a good place to ask the question. Cheers again for the detailed response
