### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [apertureless/vue-chartjs#729]
First of all thanks for an awesome vue plugin!

I see that there is very little to zero maintenance going on in this repo https://github.com/apertureless/vue-chartjs/graphs/code-frequency

I find this is posing a severy security risk to all those applications that use this plugin (which are somewhere in the order of a few thousands).

So, whats the maintenance plan? How about adding a shout-out to the README stating "supporters wanted" or alike?

I think this would make internet a little more secure...

**Comment by apertureless** [comment]
Well, to be honest after the initial implementation there were generally not much of maintenance needed.
If you check out the issues 90% are questions about usage. And a few related to the reactivity which is based off the mixins and have a lot of cases where it's not working properly. 
But all in all this is just a simple wrapper around chart.js and the additional functionality is kinda very limited and with that also limited space for bugs. 

There are basically only 2 bigger issues currently, that is vue 3 compatibility and chartjs 3 compatibility. 
However, I am pretty low on time to invest to migrate the lib. I have a branch for the chartjs 3 migration, which however gave a some headaches because of various conceptual / architectural problems with the new chartjs 3 release, which in the end need some time to figure things out, also mentioned this in other issues.

That said, recently a few open source enthusiast offered help with the maintenance and were added as collaborators. So there should be some movement in near future.

I honestly do not see any security risk at all. Feel free to elaborate more on this, but vue-chartjs has only 1 dependency and that is chart.js. 

And because it is a peerDependency you can basically manage the versions of chart.js yourself. (Only up to the supported versions which is < 3.0 currently). So even tho, there were any vulnerability in chart.js you could update it yourself.
