### ISSUE TITLE
support for vue2.7

### ISSUE THREAD

**Issue by scil** [apertureless/vue-chartjs#889]
### Would you like to work on this feature?

- [X] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

vue@^2.6.0 incluces 2.7

or peer dependency should be `vue@~2.6.0` 

### Describe the solution you'd like

I tried vue 2.7 , vue-chartjs  can not work.  maybe it should wait vue-demi.

**Comment by thabarbados** [comment]
I'll try to add support for Vue 2.7 soon.

**Comment by thabarbados** [comment]
Hey, @scil, today I tried to add support for Vue 2.7, but it turned out that the vue-chartjs has no errors in working with this Vue version.
You can see an example of how vue-chartjs works with Vue 2.7.7 [here](https://codesandbox.io/s/laughing-sun-8ol5x6?file=/package.json).

Maybe your error had another reason? Please create a reproduction of this error.
