### ISSUE TITLE
[Bug]: Bar chart from example shows no data in graph and typescript errors in vscode for chart-data and chart-options

### ISSUE THREAD

**Issue by capttrousers** [apertureless/vue-chartjs#936]
### Would you like to work on a fix?

- [X] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

Current behavior:
Chart options / data setup as follows:
```
data() {
        return {
          chartOptions: {
            responsive: false,
            indexAxis: 'y',
            scales: {
              xAxis: {
                display: false,
                ticks: {
                  display: false
          ///...
computed: {
      chartData () {
        return {
          datasets: [
            {
              barThickness: 30,
              data: [
                {x: 'a', y: 2},
                {x: 'b', y: 5},
                {x: 'c', y: 3},
                {x: 'd', y: 1},
         //...
```
And consumed in the Bar component like so:
```
        <Bar
          :chart-options="chartOptions"
          :chart-data="chartData"
          //...
```
I also added this to the vite.config.ts for types and reloaded vscode, no dice:
```
"types": [
      "vue-chartjs/dist"
    ]
```

I get typescript errors in vscode, for `chart-options` and `chart-data` saying types are incompatible.
And also no data is shown in the chart, the legend says undefined and theres just a single pixel wide line going vertical. The bar chart is supposed to be horizontal.
node: 16.14
npm: 8.3.1
vue: 3.2.38
vue-chartjs: 4.1.2
vite: 3.0.9

### Reproduction
Here's a pastebin of the entire App.vue sfc:
https://pastebin.com/Uu8qHMWs

### chart.js version

v0.3.24

### vue-chartjs version

v4.1.2

**Comment by Arantiryo** [comment]
Hi @capttrousers 👋 

If you want the chart to be horizontal, you need to flip the data around like so: 
```
data: [
  { x: 2, y: "a" },
  { x: 5, y: "b" },
  { x: 3, y: "c" },
  { x: 1, y: "d" },
],
```
You can set the `label` property to give the legend a name (instead of 'undefined'). And also remove `parsing: false` so the data can be processed by the chart. 

And you end up with the following chart:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/48175583/197343273-00ffb17c-f294-4cef-8943-79d23043692a.png">

I'm not super familiar with `Vue` so I can't comment on the type errors you are getting but according to [the docs](https://vue-chartjs.org/guide/#creating-your-first-chart) the TypeScript components are defined a little differently.

Hope that helps : )
